import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { javascriptDeclarationIdentity } from "./javascript-provider.mjs";
import { JavaScriptProjectSession, javascriptProjectRevision, reconcileJavaScriptProject } from "./javascript-project-reconcile.mjs";

const repo=path.resolve(new URL("../..",import.meta.url).pathname),fixture=path.join(repo,"fixtures/javascript-upb05-configuration"),projectPath="example.test/javascript-upb05",files=["application.js","configuration.js","controlled.js","policy.js","state.js","transport.js"];
const structuredReferences=["configuration-selection.json","durable-selection.json","transport-selection.json","controlled-effects-selection.json"];
const options=(root,out,replacement="BuildPolicy")=>({project:root,destination:out,projectPath,files,structuredReferences,moduleG1:path.join(repo,"modules/execution/v36/module.g1"),entryName:"Run",target:javascriptDeclarationIdentity(projectPath,"InitializePolicy"),expected:"InitializePolicy",replacement,revision:2,baseRevision:javascriptProjectRevision({project:root,files,structuredReferences}),nativeRunner:path.join(repo,"reference/js/javascript-upb11-native-runner.mjs")});

test("performs an identity-bound cross-module rename atomically",()=>{const work=fs.mkdtempSync(path.join(os.tmpdir(),"seme-js-reconcile-test-"));try{const out=path.join(work,"out");const result=reconcileJavaScriptProject(options(fixture,out));assert.equal(result.report.occurrences.length,3);assert.match(fs.readFileSync(path.join(out,"policy.js"),"utf8"),/function BuildPolicy/);assert.match(fs.readFileSync(path.join(out,"application.js"),"utf8"),/import \{ BuildPolicy \}/);assert.match(fs.readFileSync(path.join(out,"configuration-selection.json"),"utf8"),/"name":"BuildPolicy"/);assert.doesNotMatch(fs.readFileSync(path.join(out,"application.js"),"utf8"),/InitializePolicy/);assert.equal(result.report.target,options(fixture,out).target);assert.throws(()=>reconcileJavaScriptProject(options(fixture,out)),/javascript_reconcile\.path/);}finally{fs.rmSync(work,{recursive:true,force:true});}});
test("rejects forged identities and collisions without output",()=>{const work=fs.mkdtempSync(path.join(os.tmpdir(),"seme-js-reconcile-test-"));try{assert.throws(()=>reconcileJavaScriptProject({...options(fixture,path.join(work,"forged")),target:"00".repeat(16)}),/target_identity/);assert.throws(()=>reconcileJavaScriptProject(options(fixture,path.join(work,"collision"),"Run")),/collision/);assert.equal(fs.existsSync(path.join(work,"forged")),false);assert.equal(fs.existsSync(path.join(work,"collision")),false);}finally{fs.rmSync(work,{recursive:true,force:true});}});
test("rejects a stale native snapshot without output",()=>{const work=fs.mkdtempSync(path.join(os.tmpdir(),"seme-js-reconcile-test-"));try{const root=path.join(work,"source");fs.cpSync(fixture,root,{recursive:true});const stale=options(root,path.join(work,"out"));fs.appendFileSync(path.join(root,"policy.js"),"\n// concurrent native edit\n");assert.throws(()=>reconcileJavaScriptProject(stale),/stale_native_revision/);assert.equal(fs.existsSync(path.join(work,"out")),false);}finally{fs.rmSync(work,{recursive:true,force:true});}});
test("rejects an ambiguous semantic declaration without output",()=>{const work=fs.mkdtempSync(path.join(os.tmpdir(),"seme-js-reconcile-test-"));try{const root=path.join(work,"source");fs.cpSync(fixture,root,{recursive:true});fs.appendFileSync(path.join(root,"transport.js"),"\nexport function InitializePolicy(value) { return value; }\n");assert.throws(()=>reconcileJavaScriptProject(options(root,path.join(work,"out"))),/declaration_cardinality/);assert.equal(fs.existsSync(path.join(work,"out")),false);}finally{fs.rmSync(work,{recursive:true,force:true});}});
test("retains last valid canonical project across invalid and stale snapshots",()=>{const moduleG1=fs.readFileSync(path.join(repo,"modules/execution/v36/module.g1"),"utf8"),nativeFiles=files.map((relative)=>({path:relative,source:fs.readFileSync(path.join(fixture,relative),"utf8")}));const session=new JavaScriptProjectSession({projectPath,moduleG1,entryName:"Run"});const first=session.apply({revision:1,files:nativeFiles});assert.equal(first.disposition,"accepted-valid");const invalid=session.apply({revision:2,files:nativeFiles.map((f)=>f.path==="policy.js"?{...f,source:"export function ("}:f)});assert.equal(invalid.disposition,"accepted-invalid");assert.equal(invalid.canonicalG1,first.canonicalG1);assert.equal(invalid.lastValidRevision,1);const stale=session.apply({revision:2,files:nativeFiles});assert.equal(stale.disposition,"rejected-stale");assert.equal(stale.canonicalG1,first.canonicalG1);assert.equal(stale.lastValidRevision,1);const recovered=session.apply({revision:3,files:nativeFiles});assert.equal(recovered.disposition,"accepted-valid");assert.equal(recovered.lastValidRevision,3);});
