import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {fileURLToPath} from "node:url";
import {encodeUPB12Manifest,UPB12_REQUIRED} from "./upb12-authority.mjs";
import {verifyUPB12Descriptor} from "./upb12-descriptor.mjs";

const repo=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../.."),descriptor=path.join(repo,"conformance/upb-v1/upb-12-project.json"),fixture=path.join(repo,"fixtures/javascript-upb05-configuration");

function completeAuthority(){const {root,files}=authorityBase();for(const[name,value]of files){const target=path.join(root,...name.split("/"));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,value);}fs.writeFileSync(path.join(root,"COMPLETE.sha256"),encodeUPB12Manifest(files));return root;}
function authorityBase(){const root=fs.mkdtempSync(path.join(os.tmpdir(),"seme-upb12-descriptor-")),files=new Map(UPB12_REQUIRED.map(name=>[name,Buffer.from(`canonical ${name}\n`)])),neutral=value=>Buffer.from(value.toString().replaceAll("example.test/javascript-upb05","seme.upb12/service"));for(const[name,file]of [["configuration-selection-v1.json","configuration-selection.json"],["durable-selection-v1.json","durable-selection.json"],["transport-selection-v1.json","transport-selection.json"],["effects-selection-v1.json","controlled-effects-selection.json"]])files.set(name,neutral(fs.readFileSync(path.join(fixture,file))));for(const[digest,file]of [["247632bca93a2c19ec3212589dea38aa5a681ae910abdba4c8dce9b054c518ca","marker.bin"],["8a9796d8ef50b6b34bf659586a0926cb45caf59c4c77cb5635bf85940ca105fc","notice.txt"]])files.set(`blobs/${digest}`,fs.readFileSync(path.join(fixture,"resources",file)));return{root,files};}
test("binds the neutral descriptor to source-free project inputs",()=>{const root=completeAuthority();try{const report=verifyUPB12Descriptor(descriptor,root);assert.equal(report.identity,"seme.upb12/service");assert.deepEqual(report.languages,["go","javascript","lua"]);}finally{fs.rmSync(root,{recursive:true,force:true});}});
test("rejects descriptor and project-identity substitution",()=>{for(const kind of ["descriptor","identity"]){const root=completeAuthority(),copy=path.join(path.dirname(root),`${path.basename(root)}-${kind}.json`);try{if(kind==="descriptor"){const value=JSON.parse(fs.readFileSync(descriptor));value.target.name="native-only";fs.writeFileSync(copy,JSON.stringify(value));assert.throws(()=>verifyUPB12Descriptor(copy,root),/upb12_descriptor\.target/);}else{const selection=path.join(root,"effects-selection-v1.json"),value=JSON.parse(fs.readFileSync(selection));value.clock.owner="foreign/project";fs.writeFileSync(selection,JSON.stringify(value));const files=new Map();for(const name of UPB12_REQUIRED)files.set(name,fs.readFileSync(path.join(root,name)));for(const name of fs.readdirSync(path.join(root,"blobs")))files.set(`blobs/${name}`,fs.readFileSync(path.join(root,"blobs",name)));fs.writeFileSync(path.join(root,"COMPLETE.sha256"),encodeUPB12Manifest(files));assert.throws(()=>verifyUPB12Descriptor(descriptor,root),/upb12_descriptor\.project_identity/);}}finally{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(copy,{force:true});}}});
