#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); work=$(mktemp -d "${TMPDIR:-/tmp}/seme-js08.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM; GOCACHE="$work/go"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
source="$repo/fixtures/javascript-uab-08/program.js"; vectors="$repo/fixtures/javascript-uab-08/vectors.json"; module="$repo/modules/execution/v32/module.g1"
node "$repo/reference/js/javascript-provider-cli.mjs" --source "$source" --module "$module" --package example.test/javascript-uab-08 --revision 1 --entry IncrementPositive --out "$work/source.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"
node "$repo/reference/js/javascript-projector-cli.mjs" "$work/source.g1" "$work/projected.js"; node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/projected.js" --module "$module" --package example.test/javascript-uab-08 --revision 1 --entry IncrementPositive --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"
node "$repo/reference/js/javascript-uab-08-native-runner.mjs" "$source" "$vectors" > "$work/native.json"; node "$repo/reference/js/javascript-uab-08-native-runner.mjs" "$work/projected.js" "$vectors" > "$work/projected.json"; node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval); node "$repo/reference/js/javascript-uab-08-vectors.mjs" "$vectors" > "$work/canonical-vectors.json"; "$work/eval" "$work/program.seme" "$work/canonical-vectors.json" --named-rejections > "$work/canonical.json"
node -e 'const fs=require("fs"),u=require("util"),n=JSON.parse(fs.readFileSync(process.argv[1])).valid,c=JSON.parse(fs.readFileSync(process.argv[2]));const v=Object.fromEntries(Object.entries(c.valid).map(([k,x])=>[k,{variant:x.variant,payload:x.payload.i64}]));if(!u.isDeepStrictEqual(n,v)||!u.isDeepStrictEqual(Object.keys(c.rejected).sort(),["arity","wrong-type"]))process.exit(1)' "$work/native.json" "$work/canonical.json"
sed 's/(error) => Seme.error(error)/(error) => { throw new Error(error); }/' "$source" > "$work/throw.js"; if node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/throw.js" --module "$module" --package bad --revision 1 --entry IncrementPositive --out "$work/bad.g1" 2> "$work/bad.log"; then exit 1; fi; rg -q 'javascript\..*:[0-9][0-9]*:[0-9][0-9]*' "$work/bad.log"
echo 'JavaScript UAB-08 native/canonical evidence: exact lift, native parity, canonical parity, projection, and source rejection pass'
