#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb01-source.XXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/discover" ./cmd/project-source-discover && go build -buildvcs=false -o "$work/assemble" ./cmd/project-assemble && go build -buildvcs=false -o "$work/inventory-emit" ./cmd/source-inventory-emit)
cp -R "$repo/fixtures/javascript-uab-01" "$work/project"
mkdir "$work/project/generated" "$work/project/ignored" "$work/project/vendor"
printf '%s\n' '// Code generated by fixture; DO NOT EDIT.' 'export const generated = 1;' > "$work/project/generated/value.js"
printf '%s\n' 'ignored cache' > "$work/project/ignored/cache.bin"
printf '%s\n' 'ignored suffix' > "$work/project/local.tmp"
printf '%s\n' 'vendored notice' > "$work/project/vendor/NOTICE"
printf '%s\n' 'opaque project note' > "$work/project/README.md"

discover() {
  "$work/discover" -root "$work/project" -identity example.test/javascript-upb01 \
    -language javascript -toolchain "$(node --version)" \
    -profile seme.javascript-upb01/v1 \
    -semantic-revision seme.javascript-provider/uab11 \
    -tracked-extensions .js -ignored-prefixes ignored/ \
    -ignored-suffixes .tmp -vendored-prefixes vendor/ \
    -generated-header '// Code generated' -out "$1"
}
discover "$work/a.json"
discover "$work/b.json"
cmp "$work/a.json" "$work/b.json"
node -e '
const s=JSON.parse(require("fs").readFileSync(process.argv[1]));
const got=Object.fromEntries(s.Units.map(u=>[u.Path,[u.Class,u.Preservation]]));
const want={"README.md":["opaque","byte-exact"],"application.js":["tracked","semantic-projection"],"generated/value.js":["generated","byte-exact"],"ignored/cache.bin":["ignored","byte-exact"],"local.tmp":["ignored","byte-exact"],"math/sum.js":["tracked","semantic-projection"],"seme-package-manifest.json":["opaque","byte-exact"],"vendor/NOTICE":["vendored","byte-exact"]};
if(JSON.stringify(got)!==JSON.stringify(want)||!/^[0-9a-f]{64}$/.test(s.ContentRevision)) process.exit(1);
' "$work/a.json"

if discover "$work/a.json" >"$work/collision.out" 2>"$work/collision.err"; then exit 1; fi
grep -q 'project_source_discover.output_exists' "$work/collision.err"
ln -s application.js "$work/project/alias.js"
if discover "$work/rejected.json" >"$work/symlink.out" 2>"$work/symlink.err"; then exit 1; fi
grep -q 'project_source.symlink:alias.js' "$work/symlink.err"
test ! -e "$work/rejected.json"

# A JavaScript-produced canonical execution binds directly to neutral Project
# v1; no Go source lift participates in this assembly.
(cd "$work/project" && node "$repo/reference/js/javascript-package-provider-cli.mjs" \
  --files application.js,math/sum.js \
  --module "$repo/modules/execution/v35/module.g1" \
  --package example.test/javascript-upb01 --entry Run --revision 1 \
  --out "$work/execution.g1")
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" \
  "$work/execution.g1" "$work/execution.seme"
assemble() {
  "$work/assemble" -execution "$work/execution.seme" \
    -manifest "$repo/fixtures/javascript-uab-01/seme-package-manifest.json" \
    -execution-contract "$repo/modules/execution/v35/module.seme" \
    -package-contract "$repo/modules/package/v1/module.seme" \
    -project-contract "$repo/modules/project/v1/module.seme" -out "$1"
}
assemble "$work/project-a.seme"
assemble "$work/project-b.seme"
cmp "$work/project-a.seme" "$work/project-b.seme"
if assemble "$work/project-a.seme" >"$work/project-collision.out" 2>"$work/project-collision.err"; then exit 1; fi
grep -q 'project_assemble.output_exists' "$work/project-collision.err"

emit_inventory() {
  "$work/inventory-emit" -snapshot "$work/a.json" -project "$work/project-a.seme" \
    -execution-contract "$repo/modules/execution/v35/module.seme" \
    -package-contract "$repo/modules/package/v1/module.seme" \
    -project-contract "$repo/modules/project/v2/module.seme" -out "$1"
}
emit_inventory "$work/inventory-a.seme"
emit_inventory "$work/inventory-b.seme"
cmp "$work/inventory-a.seme" "$work/inventory-b.seme"
if emit_inventory "$work/inventory-a.seme" >"$work/inventory-collision.out" 2>"$work/inventory-collision.err"; then exit 1; fi
grep -q 'source_inventory_emit.output_exists' "$work/inventory-collision.err"

echo 'JavaScript UPB-01 foundation: deterministic source inventory binds to neutral Project-v2 authority'
