#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; pulp_commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-go08-full.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM; GOCACHE="$work/go"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
fixture="$repo/fixtures/go-uab-08"; vectors="$fixture/vectors.json"; module="$repo/modules/execution/v32/module.g1"
(cd "$repo/reference/go" && go test -buildvcs=false ./goprovider ./goprojector ./canonicaleval ./wasmtarget && go build -buildvcs=false -o "$work/session" ./cmd/go-session-proof && go build -buildvcs=false -o "$work/projector" ./cmd/go-projector && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
(cd "$fixture" && go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/native.json")
"$work/session" --module "$module" --project "$fixture" --package example.test/go-uab-08 --revision 1 --entry IncrementPositive --out "$work/source.g1"
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/kernel-wire-validator.k0" "$work/program.seme"
"$work/projector" -package fallible "$work/source.g1" "$work/projected.go"; mkdir -p "$work/projected/cmd/native-observations"; cp "$fixture/go.mod" "$work/projected/go.mod"; cp "$work/projected.go" "$work/projected/program.go"; cp "$fixture/cmd/native-observations/main.go" "$work/projected/cmd/native-observations/main.go"
(cd "$work/projected" && go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/projected.json"); node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
"$work/session" --module "$module" --project "$work/projected" --package example.test/go-uab-08 --revision 1 --entry IncrementPositive --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"
node "$repo/reference/js/javascript-uab-08-vectors.mjs" "$vectors" > "$work/canonical-vectors.json"; "$work/eval" "$work/program.seme" "$work/canonical-vectors.json" --named-rejections > "$work/canonical.json"
"$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"; node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/program.wasm" "$vectors" > "$work/wasm.json"
node -e 'const fs=require("fs"),u=require("util"),n=JSON.parse(fs.readFileSync(process.argv[1])).valid,c=JSON.parse(fs.readFileSync(process.argv[2])),w=JSON.parse(fs.readFileSync(process.argv[3]));const cv=Object.fromEntries(Object.entries(c.valid).map(([k,v])=>[k,{variant:v.variant,payload:v.payload.i64}]));if(!u.isDeepStrictEqual(n,cv)||!u.isDeepStrictEqual(n,w.valid)||!u.isDeepStrictEqual(Object.keys(c.rejected).sort(),["arity","wrong-type"])||!u.isDeepStrictEqual(w.malformed,["empty","short","long"]))process.exit(1)' "$work/native.json" "$work/canonical.json" "$work/wasm.json"
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$pulp_commit^{commit}"; mkdir "$work/pinned" "$work/pulp"; git -C "$pulp_repo" archive "$pulp_commit" | tar -x -C "$work/pinned"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$work/program.wasm" "$work/pulp/pure-function.wasm"
node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/program.wasm" "$vectors" --tsv > "$work/requests.tsv"; : > "$work/pulp-audit.tsv"; tab=$(printf '\t'); while IFS="$tab" read -r kind name request response; do if [ "$kind" = valid ]; then (cd "$work/pulp" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") > "$work/$name.log" 2>&1; rg -q "\"response\":\"$response\"" "$work/$name.log"; elif (cd "$work/pulp" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") >/dev/null 2>&1; then exit 1; fi; printf '%s\t%s\n' "$kind" "$name" >> "$work/pulp-audit.tsv"; done < "$work/requests.tsv"
node -e 'const fs=require("fs"),f=p=>fs.readFileSync(p,"utf8").trim().split("\n").map(x=>x.split("\t").slice(0,2));require("assert").deepStrictEqual(f(process.argv[1]),f(process.argv[2]))' "$work/requests.tsv" "$work/pulp-audit.tsv"
cp -R "$fixture" "$work/source-reject"; sed -i 's/Error: 99/Error: "wrong"/' "$work/source-reject/program.go"; if "$work/session" --module "$module" --project "$work/source-reject" --package example.test/go-uab-08-bad --revision 1 --entry IncrementPositive --out "$work/bad.g1" 2> "$work/bad.log"; then echo 'accepted incompatible error payload' >&2; exit 1; fi; rg -q 'File:"program.go", Line:[1-9][0-9]*' "$work/bad.log"
result_ok=$(awk '$3 == "00000000000000000000000000009043" { print $2; exit }' "$work/source.g1"); integer=$(awk '$3 == "00000000000000000000000000009010" { print $2; exit }' "$work/source.g1"); entry=$(awk '$3 == "00000000000000000000000000009015" {p=$2} $1=="fi"&&$2=="00000000000000000000000000009151"{print $4}' "$work/source.g1")
: > "$work/graph-audit.tsv"; sed "0,/fi 00000000000000000000000000009410 rf [0-9a-f]*/s//fi 00000000000000000000000000009410 rf $integer/" "$work/source.g1" > "$work/wrong-result-type.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/wrong-result-type.g1" "$work/wrong-result-type.seme"; if "$work/lower" "$work/wrong-result-type.seme" "$work/x.wasm" "$work/x.json" >/dev/null 2>&1; then echo 'accepted forged result constructor type' >&2; exit 1; fi; printf 'graph-reject\twrong-result-type\n' >> "$work/graph-audit.tsv"
call=$(awk '$3 == "00000000000000000000000000009060" { print $2; exit }' "$work/source.g1"); sed "0,/fi 00000000000000000000000000009600 rf [0-9a-f]*/s//fi 00000000000000000000000000009600 rf $entry/" "$work/source.g1" > "$work/cycle.g1"; if "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/cycle.g1" "$work/cycle.seme" >/dev/null 2>&1; then if "$work/lower" "$work/cycle.seme" "$work/y.wasm" "$work/y.json" >/dev/null 2>&1; then echo 'accepted recursive propagation graph' >&2; exit 1; fi; fi; printf 'graph-reject\tcycle\n' >> "$work/graph-audit.tsv"
node -e 'const fs=require("fs");require("assert").deepStrictEqual(fs.readFileSync(process.argv[1],"utf8").trim().split("\n"),["graph-reject\twrong-result-type","graph-reject\tcycle"])' "$work/graph-audit.tsv"
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.go["UAB-08"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'Go UAB-08 complete acceptance: all five evidence classes pass'
