#!/bin/sh
# Full Lua UPB11 reconciliation, rebuild, placement, and Project-v14 proof.
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd);fixture="$repo/fixtures/lua-upb05-configuration";work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb11-project.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM;GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
files=application.lua,configuration.lua,controlled.lua,policy.lua,state.lua,transport.lua;structured=configuration-selection.json,durable-selection.json,transport-selection.json,controlled-effects-selection.json;project=example.test/lua-upb05;target=80555555555555555555555555555506
(cd "$repo/reference/go"&&go build -buildvcs=false -o "$work/bundle" ./cmd/project-v12-bundle&&go build -buildvcs=false -o "$work/place" ./cmd/go-upb10-place&&go build -buildvcs=false -o "$work/finalize" ./cmd/project-v14-finalize&&GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -buildvcs=false -o "$work/canonical-vm.wasm" ./cmd/canonical-wasm-cell);cp "$repo/targets/wasm/pulp-canonical-vm-v1/pulp.cell.toml" "$work/pulp.cell.toml"
base_revision=$(node --input-type=module - "$repo/reference/lua/lua-project-reconcile.mjs" "$fixture" <<'NODE'
const{luaProjectRevision:r}=await import(process.argv[2]);process.stdout.write(r({project:process.argv[3],files:["application.lua","configuration.lua","controlled.lua","policy.lua","state.lua","transport.lua"],structuredReferences:["configuration-selection.json","durable-selection.json","transport-selection.json","controlled-effects-selection.json"]}));
NODE
)
node "$repo/reference/lua/lua-project-reconcile-cli.mjs" --project "$fixture" --out "$work/result-source" --project-path "$project" --files "$files" --structured-references "$structured" --module "$repo/modules/execution/v36/module.g1" --entry Run --target "$target" --expected InitializePolicy --replacement BuildPolicy --revision 2 --base-revision "$base_revision" --native-runner "$repo/reference/lua/lua-upb11-native.lua" --native-adapter "$repo/reference/lua/seme-values.lua"
node "$repo/reference/lua/lua-project-reconcile-verify-cli.mjs" --project "$work/result-source" --project-path "$project" --files "$files" --structured-references "$structured" --module "$repo/modules/execution/v36/module.g1" --entry Run --native-runner "$repo/reference/lua/lua-upb11-native.lua" --native-adapter "$repo/reference/lua/seme-values.lua" >"$work/reconciliation-report.json"
if test -n "${LUA_UPB10_INPUT:-}";then test -d "$LUA_UPB10_INPUT/base";test -d "$LUA_UPB10_INPUT/placement";cp -R "$LUA_UPB10_INPUT/base" "$work/prior-base";cp -R "$LUA_UPB10_INPUT/placement" "$work/prior-placement";else LUA_UPB10_EXPORT="$work/prior-upb10" "$repo/scripts/check-lua-upb-10-placement.sh";cp -R "$work/prior-upb10/base" "$work/prior-base";cp -R "$work/prior-upb10/placement" "$work/prior-placement";fi
echo 'Lua UPB-11 project stage: rebuild reconciled semantic revision'
LUA_UPB_FIXTURE="$work/result-source" LUA_UPB_PROJECT="$project" LUA_UPB_REVISION=2 LUA_UPB09_EXPORT="$work/result-upb09" "$repo/scripts/check-lua-upb-09-foundation.sh"
"$work/bundle" -bundle-v11 "$work/result-upb09/v11-bundle" -extension-v12 "$work/result-upb09/v12" -out "$work/result-base"
common_place(){ bundle=$1;selection_root=$2;shift 2;"$work/place" -bundle "$bundle" -selection "$selection_root/configuration-selection.json" -durable-selection "$selection_root/durable-selection.json" -transport-selection "$selection_root/transport-selection.json" -effects-selection "$selection_root/controlled-effects-selection.json" -foundation "$repo/modules/foundation/v1/module.seme" -execution "$repo/modules/execution/v36/module.seme" -package "$repo/modules/package/v4/module.seme" -dependency "$repo/modules/dependency/v1/module.seme" -configuration "$repo/modules/configuration/v3/module.seme" -resource "$repo/modules/resource/v1/module.seme" -durable-state "$repo/modules/durable-state/v1/module.seme" -source-presentation "$repo/modules/source-presentation/v1/module.seme" -ordered-transport "$repo/modules/ordered-transport/v1/module.seme" -controlled-effects "$repo/modules/controlled-effects/v1/module.seme" -target "$repo/modules/target/v1/module.seme" -project-v8 "$repo/modules/project/v8/module.seme" -project-v9 "$repo/modules/project/v9/module.seme" -project-v10 "$repo/modules/project/v10/module.seme" -project-v11 "$repo/modules/project/v11/module.seme" -project-v12 "$repo/modules/project/v12/module.seme" -project-v13 "$repo/modules/project/v13/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -canonical-vm "$work/canonical-vm.wasm" -pulp-cell "$work/pulp.cell.toml" -target-name wasm32-pulp-lua-host-v1 -rule-namespace lua-upb10 "$@";}
common_place "$work/result-base" "$work/result-source" -out "$work/result-placement"
finalize(){ destination=$1;reconciliation=${2:-"$work/result-source"};"$work/finalize" -bundle "$work/prior-base" -placement "$work/prior-placement" -selection "$fixture/configuration-selection.json" -durable-selection "$fixture/durable-selection.json" -transport-selection "$fixture/transport-selection.json" -effects-selection "$fixture/controlled-effects-selection.json" -result-bundle "$work/result-base" -result-placement "$work/result-placement" -result-selection "$work/result-source/configuration-selection.json" -reconciliation "$reconciliation" -language lua -project-identity "$project" -target-name wasm32-pulp-lua-host-v1 -rule-namespace lua-upb10 -reconciliation-label seme-lua-reconciliation-v1 -identity-evidence-required=false -foundation "$repo/modules/foundation/v1/module.seme" -execution "$repo/modules/execution/v36/module.seme" -package "$repo/modules/package/v4/module.seme" -dependency "$repo/modules/dependency/v1/module.seme" -configuration "$repo/modules/configuration/v3/module.seme" -resource "$repo/modules/resource/v1/module.seme" -durable-state "$repo/modules/durable-state/v1/module.seme" -source-presentation "$repo/modules/source-presentation/v1/module.seme" -ordered-transport "$repo/modules/ordered-transport/v1/module.seme" -controlled-effects "$repo/modules/controlled-effects/v1/module.seme" -target "$repo/modules/target/v1/module.seme" -project-v8 "$repo/modules/project/v8/module.seme" -project-v9 "$repo/modules/project/v9/module.seme" -project-v10 "$repo/modules/project/v10/module.seme" -project-v11 "$repo/modules/project/v11/module.seme" -project-v12 "$repo/modules/project/v12/module.seme" -project-v13 "$repo/modules/project/v13/module.seme" -patch "$repo/modules/patch/v1/module.seme" -language-service "$repo/modules/language-service/v1/module.seme" -project-v14 "$repo/modules/project/v14/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$destination";}
finalize "$work/final-a";finalize "$work/final-b";diff -ru "$work/final-a" "$work/final-b";test -s "$work/final-a/patch-v1.seme";test -s "$work/final-a/project-v14.seme"
if finalize "$work/final-a" >"$work/collision.out" 2>"$work/collision.err";then echo 'Lua UPB-11 overwrote final authority' >&2;exit 1;fi;test ! -s "$work/collision.out"
cp -R "$work/result-source" "$work/tampered";printf x >>"$work/tampered/.seme-reconciliation-v1/projection-report.json";if finalize "$work/tampered-final" "$work/tampered" >"$work/tampered.out" 2>"$work/tampered.err";then echo 'Lua UPB-11 finalizer accepted reconciliation tamper' >&2;exit 1;fi;test ! -e "$work/tampered-final";test ! -s "$work/tampered.out"
if test -n "${LUA_UPB11_EXPORT:-}";then test ! -e "$LUA_UPB11_EXPORT";mkdir "$LUA_UPB11_EXPORT";cp -R "$work/result-source" "$LUA_UPB11_EXPORT/source";cp -R "$work/prior-base" "$LUA_UPB11_EXPORT/prior-base";cp -R "$work/result-base" "$LUA_UPB11_EXPORT/result-base";cp -R "$work/prior-placement" "$LUA_UPB11_EXPORT/prior-placement";cp -R "$work/result-placement" "$LUA_UPB11_EXPORT/result-placement";cp -R "$work/final-a" "$LUA_UPB11_EXPORT/final";fi
echo 'Lua UPB-11 full Project-v14 reconciliation and deterministic publication pass'
