#!/bin/sh
# Deterministic Lua project snapshot, Project-v2 authority, and round trip.
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb01-source.XXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
identity=seme.uab11/application
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/discover" ./cmd/project-source-discover && go build -buildvcs=false -o "$work/assemble" ./cmd/project-assemble && go build -buildvcs=false -o "$work/inventory" ./cmd/source-inventory-emit && go build -buildvcs=false -o "$work/publish" ./cmd/project-roundtrip-publish)
mkdir "$work/project"
cp "$repo/fixtures/lua-uab-11/policy.lua" "$work/project/policy.lua"
cp "$repo/fixtures/lua-uab-11/application.lua" "$work/project/application.lua"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/project/policy.lua" --source "$work/project/application.lua" --module "$repo/modules/execution/v35/module.g1" --package "$identity" --revision 1 --entry Apply --out "$work/execution.g1"
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/execution.g1" "$work/execution.seme"
node "$repo/reference/lua/lua-project-manifest.mjs" "$work/execution.g1" "$identity" "$work/project/seme-package-manifest.json"
mkdir "$work/project/generated" "$work/project/ignored" "$work/project/vendor"
printf '%s\n' '-- Code generated by fixture; DO NOT EDIT.' 'return true' > "$work/project/generated/value.lua"
printf '%s\n' 'ignored cache' > "$work/project/ignored/cache.bin"
printf '%s\n' 'ignored suffix' > "$work/project/local.tmp"
printf '%s\n' 'vendored notice' > "$work/project/vendor/NOTICE"
printf '%s\n' 'opaque Lua project note' > "$work/project/README.md"

discover(){ "$work/discover" -root "$work/project" -identity "$identity" -language lua -toolchain "$(nvim --version | sed -n '1p')" -profile seme.lua-upb01/v1 -semantic-revision seme.lua-provider/uab11 -tracked-extensions .lua -ignored-prefixes ignored/ -ignored-suffixes .tmp -vendored-prefixes vendor/ -generated-header '-- Code generated' -out "$1"; }
discover "$work/snapshot-a.json"; discover "$work/snapshot-b.json"; cmp "$work/snapshot-a.json" "$work/snapshot-b.json"
node - "$work/snapshot-a.json" <<'NODE'
const s=JSON.parse(require("fs").readFileSync(process.argv[2])),got=Object.fromEntries(s.Units.map(u=>[u.Path,[u.Class,u.Preservation]])),want={"README.md":["opaque","byte-exact"],"application.lua":["tracked","semantic-projection"],"generated/value.lua":["generated","byte-exact"],"ignored/cache.bin":["ignored","byte-exact"],"local.tmp":["ignored","byte-exact"],"policy.lua":["tracked","semantic-projection"],"seme-package-manifest.json":["opaque","byte-exact"],"vendor/NOTICE":["vendored","byte-exact"]};if(JSON.stringify(got)!==JSON.stringify(want)||!/^[0-9a-f]{64}$/.test(s.ContentRevision))process.exit(1);
NODE
if discover "$work/snapshot-a.json" >"$work/collision.out" 2>"$work/collision.err";then exit 1;fi
test ! -s "$work/collision.out"; rg -q 'output_exists' "$work/collision.err"
ln -s application.lua "$work/project/alias.lua"
if discover "$work/symlink.json" >"$work/symlink.out" 2>"$work/symlink.err";then exit 1;fi
test ! -e "$work/symlink.json"; rg -q 'project_source.symlink' "$work/symlink.err"; rm "$work/project/alias.lua"

assemble(){ "$work/assemble" -execution "$work/execution.seme" -manifest "$work/project/seme-package-manifest.json" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v1/module.seme" -out "$1"; }
assemble "$work/project-a.seme"; assemble "$work/project-b.seme"; cmp "$work/project-a.seme" "$work/project-b.seme"
inventory(){ "$work/inventory" -snapshot "$work/snapshot-a.json" -project "$work/project-a.seme" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v2/module.seme" -out "$1"; }
inventory "$work/inventory-a.seme"; inventory "$work/inventory-b.seme"; cmp "$work/inventory-a.seme" "$work/inventory-b.seme"

node "$repo/reference/lua/lua-projector-cli.mjs" "$work/execution.g1" "$work/projected.lua"
: > "$work/no-policy.lua"
"$work/publish" -root "$work/project" -snapshot "$work/snapshot-a.json" -dest "$work/projected-native" -projected "seme_projected.lua=$work/projected.lua" -tracked-extensions .lua -ignored-prefixes ignored/ -ignored-suffixes .tmp -vendored-prefixes vendor/ -generated-header '-- Code generated'
for name in README.md generated/value.lua ignored/cache.bin local.tmp seme-package-manifest.json vendor/NOTICE;do cmp "$work/project/$name" "$work/projected-native/$name";done
test ! -e "$work/projected-native/application.lua"; test ! -e "$work/projected-native/policy.lua"
node "$repo/reference/lua/lua-uab-11-corpus.mjs" > "$work/corpus.json"
env XDG_DATA_HOME="$work/native-data" XDG_STATE_HOME="$work/native-state" XDG_CACHE_HOME="$work/native-cache" nvim -l "$repo/reference/lua/lua-uab-11-native.lua" "$repo/reference/lua/seme-values.lua" "$work/project/policy.lua" "$work/project/application.lua" "$work/corpus.json" > "$work/native.json"
env XDG_DATA_HOME="$work/projected-data" XDG_STATE_HOME="$work/projected-state" XDG_CACHE_HOME="$work/projected-cache" nvim -l "$repo/reference/lua/lua-uab-11-native.lua" "$repo/reference/lua/seme-values.lua" "$work/no-policy.lua" "$work/projected-native/seme_projected.lua" "$work/corpus.json" > "$work/projected.json"
node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/projected-native/seme_projected.lua" --module "$repo/modules/execution/v35/module.g1" --package "$identity" --revision 1 --entry Apply --out "$work/relift.g1"
cmp "$work/execution.g1" "$work/relift.g1"

cp -R "$work/project" "$work/drifted"
printf x >> "$work/drifted/README.md"
if "$work/publish" -root "$work/drifted" -snapshot "$work/snapshot-a.json" -dest "$work/drift-output" -projected "seme_projected.lua=$work/projected.lua" -tracked-extensions .lua -ignored-prefixes ignored/ -ignored-suffixes .tmp -vendored-prefixes vendor/ -generated-header '-- Code generated' >"$work/drift.out" 2>"$work/drift.err";then exit 1;fi
test ! -e "$work/drift-output"; test ! -s "$work/drift.out"; rg -q 'digest' "$work/drift.err"
if "$work/publish" -root "$work/project" -snapshot "$work/snapshot-a.json" -dest "$work/projected-native" -projected "seme_projected.lua=$work/projected.lua" -tracked-extensions .lua -ignored-prefixes ignored/ -ignored-suffixes .tmp -vendored-prefixes vendor/ -generated-header '-- Code generated' >"$work/publish.out" 2>"$work/publish.err";then exit 1;fi
test ! -s "$work/publish.out"; rg -q 'destination_exists' "$work/publish.err"
printf 'Lua UPB-01 source authority: deterministic snapshot, Project-v2, native round trip, exact re-lift, preservation, and atomic adversaries pass\n'
