#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd);fixture="$repo/fixtures/lua-upb05-configuration";project=example.test/lua-upb05;work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb05.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go"&&for command in project-source-discover project-assemble source-inventory-emit package-detail-emit package-v4-upgrade dependency-emit project-v8-compose go-upb05-configure;do go build -buildvcs=false -o "$work/$command" "./cmd/$command";done)
provider(){ node "$repo/reference/lua/lua-provider-cli.mjs" --source "$1/application.lua" --source "$1/configuration.lua" --source "$1/policy.lua" --source "$1/state.lua" --module "$repo/modules/execution/v36/module.g1" --package "$project" --revision 1 --entry Run --out "$2"; }
provider "$fixture" "$work/construction.g1";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/construction.g1" "$work/execution.seme"
"$work/project-source-discover" -root "$fixture" -identity "$project" -language lua -toolchain "$(nvim --version|sed -n '1p')" -profile seme.lua-upb05/v1 -semantic-revision seme.lua-provider/upb05 -tracked-extensions .lua -generated-header '-- Code generated' -out "$work/snapshot.json"
(cd "$fixture"&&node "$repo/reference/lua/lua-project-graph-cli.mjs" --files application.lua,configuration.lua,policy.lua,state.lua --snapshot "$work/snapshot.json" --canonical-g1 "$work/construction.g1" --project "$project" --root-module application.lua --out "$work/graph.json")
node "$repo/reference/project/project-manifest-cli.mjs" --project "$project" --graph "$work/graph.json" --out "$work/manifest.json"
"$work/project-assemble" -execution "$work/execution.seme" -manifest "$work/manifest.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/project-base.seme"
"$work/source-inventory-emit" -snapshot "$work/snapshot.json" -project "$work/project-base.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/inventory.seme"
"$work/package-detail-emit" -base "$work/project-base.seme" -inventory "$work/inventory.seme" -graph "$work/graph.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v2.seme"
"$work/package-v4-upgrade" -package "$work/package-v2.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v4.seme"
node "$repo/reference/lua/lua-rock-resolver-cli.mjs" --rockspec "$fixture/seme-lua-upb05-1.0-1.rockspec" --lock "$fixture/seme-rock.lock.json" --local-root "$fixture" --local-files configuration.lua --external-root "$repo/fixtures/lua-upb03-external-checksum" --external-files checksum.lua,seme-checksum-1.2.3-1.rockspec --local-identity "$project/configuration" --local-from "$project/application" --external-source file:../lua-upb03-external-checksum --out "$work/closure.json";"$work/dependency-emit" -closure "$work/closure.json" -contract "$repo/modules/dependency/v1/module.seme" -out "$work/dependency.seme"
compose(){ destination=$1;selection=${2:-"$fixture/configuration-selection.json"};"$work/project-v8-compose" -construction "$work/construction.g1" -project-base "$work/project-base.seme" -inventory "$work/inventory.seme" -package-v2 "$work/package-v2.seme" -package-v4 "$work/package-v4.seme" -dependency "$work/dependency.seme" -selection "$selection" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$destination"; }
compose "$work/v8-a";compose "$work/v8-b";cmp "$work/v8-a/configuration-v3.seme" "$work/v8-b/configuration-v3.seme";cmp "$work/v8-a/project-v8.seme" "$work/v8-b/project-v8.seme"
mkdir "$work/bundle";cp "$work/construction.g1" "$work/bundle/construction-v36.g1";cp "$work/execution.seme" "$work/bundle/execution-v36.seme";cp "$work/project-base.seme" "$work/bundle/project-base-v8.seme";cp "$work/inventory.seme" "$work/bundle/inventory-v8.seme";cp "$work/package-v2.seme" "$work/bundle/package-detail-v4.seme";cp "$work/package-v4.seme" "$work/bundle/package-v4.seme";cp "$work/dependency.seme" "$work/bundle/dependency-v1.seme";cp "$work/v8-a/configuration-v3.seme" "$work/bundle/configuration-v3.seme";cp "$work/v8-a/project-v8.seme" "$work/bundle/project-v8.seme";printf 'seme-go-upb05-bundle-v2\n' > "$work/bundle/COMPLETE.sha256";for name in construction-v36.g1 execution-v36.seme project-base-v8.seme inventory-v8.seme package-detail-v4.seme package-v4.seme dependency-v1.seme configuration-v3.seme project-v8.seme;do printf '%s %s\n' "$name" "$(sha256sum "$work/bundle/$name"|cut -d ' ' -f1)" >> "$work/bundle/COMPLETE.sha256";done
printf '%s\n' '{"configuration_inputs":{},"runtime_inputs":{},"capability_grants":[]}'|"$work/go-upb05-configure" -bundle "$work/bundle" -selection "$fixture/configuration-selection.json" -foundation "$repo/modules/foundation/v1/module.seme" -execution "$repo/modules/execution/v36/module.seme" -package "$repo/modules/package/v4/module.seme" -dependency "$repo/modules/dependency/v1/module.seme" -configuration "$repo/modules/configuration/v3/module.seme" -project "$repo/modules/project/v8/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" > "$work/executed.json"
node -e 'const r=JSON.parse(require("fs").readFileSync(process.argv[1]));if(r.execution.outputs.length!==3||r.execution.lifecycle.length!==6)throw Error("lifecycle");const x=r.execution.outputs[2].result;if(x.kind!=="result"||x.variant!=="ok"||x.payload.fields.Ready.bool!==true||x.payload.fields.Total.i64!=="16"||x.payload.fields.Namespace.text!=="seme")throw Error("result")' "$work/executed.json"
node "$repo/reference/lua/lua-module-projector-cli.mjs" "$work/construction.g1" "$work/graph.json" "$work/projected";provider "$work/projected" "$work/relift.g1";cmp "$work/construction.g1" "$work/relift.g1"
if compose "$work/v8-a" >"$work/collision.out" 2>"$work/collision.err";then exit 1;fi;test ! -s "$work/collision.out";sed 's/"dependencies":\["configuration"\]/"dependencies":["missing"]/' "$fixture/configuration-selection.json" > "$work/bad-selection.json";if compose "$work/reject-selection" "$work/bad-selection.json" >"$work/selection.out" 2>"$work/selection.err";then exit 1;fi;test ! -e "$work/reject-selection"
cp -R "$fixture" "$work/ambient";printf '\nlocal forbidden = os.getenv("HOME")\n' >> "$work/ambient/application.lua";if provider "$work/ambient" "$work/ambient.g1" >"$work/ambient.out" 2>"$work/ambient.err";then exit 1;fi;test ! -e "$work/ambient.g1"
if test -n "${LUA_UPB05_EXPORT:-}";then test ! -e "$LUA_UPB05_EXPORT";mkdir "$LUA_UPB05_EXPORT";cp -R "$work/bundle" "$LUA_UPB05_EXPORT/bundle";cp "$work/snapshot.json" "$LUA_UPB05_EXPORT/snapshot.json";cp "$work/graph.json" "$LUA_UPB05_EXPORT/graph.json";fi
echo 'Lua UPB-05 foundation: neutral Configuration-v3 and Project-v8 authorities reproduce'
