#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; pulp_commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua06.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
source="$repo/fixtures/lua-uab-06/program.lua"; vectors="$repo/fixtures/lua-uab-06/vectors.json"; module="$repo/modules/execution/v29/module.g1"
(cd "$repo/reference/go" && go test -buildvcs=false ./canonicaleval ./wasmtarget && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$pulp_commit^{commit}"; mkdir "$work/pulp-pinned"; git -C "$pulp_repo" archive "$pulp_commit" | tar -x -C "$work/pulp-pinned"; (cd "$work/pulp-pinned" && go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof)
for pair in Immutable:immutable Mutable:mutable; do
  entry=${pair%%:*}; family=${pair#*:}
  node "$repo/reference/lua/lua-provider-cli.mjs" --source "$source" --module "$module" --package example.test/lua-uab-06 --revision 1 --entry "$entry" --out "$work/$family.g1"
  "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/$family.g1" "$work/$family.seme"
  "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/kernel-wire-validator.k0" "$work/$family.seme"
  "$repo/bootstrap/seme-k0-linux-amd64" "$repo/modules/foundation/v1/validator.k0" "$work/$family.seme"
  node "$repo/reference/lua/lua-projector-cli.mjs" "$work/$family.g1" "$work/$family.lua"
  node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/$family.lua" --module "$module" --package example.test/lua-uab-06 --revision 1 --entry "$entry" --out "$work/$family-relift.g1"; cmp "$work/$family.g1" "$work/$family-relift.g1"
  env XDG_DATA_HOME="$work/data-original-$family" XDG_STATE_HOME="$work/state-original-$family" XDG_CACHE_HOME="$work/cache-original-$family" nvim -l "$repo/reference/lua/lua-uab-06-native.lua" "$source" "$vectors" "$family" 2> "$work/$family-original.json"
  env XDG_DATA_HOME="$work/data-projected-$family" XDG_STATE_HOME="$work/state-projected-$family" XDG_CACHE_HOME="$work/cache-projected-$family" nvim -l "$repo/reference/lua/lua-uab-06-native.lua" "$work/$family.lua" "$vectors" "$family" 2> "$work/$family-projected.json"
  node "$repo/reference/js/javascript-uab-06-vectors.mjs" "$vectors" "$family" > "$work/$family-canonical-vectors.json"; "$work/eval" "$work/$family.seme" "$work/$family-canonical-vectors.json" --named-rejections > "$work/$family-canonical.json"
  "$work/lower" "$work/$family.seme" "$work/$family.wasm" "$work/$family-abi.json"; node "$repo/reference/js/javascript-uab-06-wasm-runner.mjs" "$work/$family.wasm" "$vectors" "$family" > "$work/$family-wasm.json"
  if [ "$family" = mutable ]; then for forgery in capture-type update-capture; do node "$repo/reference/lua/lua-uab-06-forge.mjs" "$work/$family.g1" "$work/$forgery.g1" "$forgery"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/$forgery.g1" "$work/$forgery.seme"; if "$work/lower" "$work/$forgery.seme" "$work/$forgery.wasm" "$work/$forgery.json" > "$work/$forgery.log" 2>&1; then echo "target accepted Lua closure forgery $forgery" >&2; exit 1; fi; rg -q 'wasm.mutable_closure_' "$work/$forgery.log"; done; fi
  node -e 'const fs=require("fs"),u=require("util"),p=JSON.parse(fs.readFileSync(process.argv[1])).valid,o=JSON.parse(fs.readFileSync(process.argv[2])).valid,c=JSON.parse(fs.readFileSync(process.argv[3])),w=JSON.parse(fs.readFileSync(process.argv[4])),v=JSON.parse(fs.readFileSync(process.argv[5]))[process.argv[6]],e=Object.fromEntries(v.map(x=>[x.name,x.result])),ce=Object.fromEntries(Object.entries(c.valid).map(([k,x])=>[k,x.i64]));if(!u.isDeepStrictEqual(o,e)||!u.isDeepStrictEqual(p,e)||!u.isDeepStrictEqual(ce,e)||!u.isDeepStrictEqual(w.valid,e))process.exit(1);if(!u.isDeepStrictEqual(Object.keys(c.rejected).sort(),["arity","wrong-type"])||!u.isDeepStrictEqual(w.malformed,[process.argv[6]+"-empty",process.argv[6]+"-short",process.argv[6]+"-long"]))process.exit(1)' "$work/$family-projected.json" "$work/$family-original.json" "$work/$family-canonical.json" "$work/$family-wasm.json" "$vectors" "$family"
  mkdir "$work/pulp-$family"; cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp-$family/pulp.cell.toml"; cp "$work/$family.wasm" "$work/pulp-$family/pure-function.wasm"
  node "$repo/reference/js/javascript-uab-06-wasm-runner.mjs" "$work/$family.wasm" "$vectors" "$family" --tsv > "$work/$family.tsv"; : > "$work/$family-pulp-ledger.tsv"; while IFS= read -r row; do kind=$(printf '%s\n' "$row"|cut -f1); name=$(printf '%s\n' "$row"|cut -f2); request=$(printf '%s\n' "$row"|cut -f3); response=$(printf '%s\n' "$row"|cut -f4); if [ "$kind" = valid ]; then (cd "$work/pulp-$family" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") > "$work/$name.log" 2>&1; rg -q "\"response\":\"$response\"" "$work/$name.log"; else if (cd "$work/pulp-$family" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") >/dev/null 2>&1; then echo "Pulp accepted $name" >&2; exit 1; fi; fi; printf '%s\n' "$row" >> "$work/$family-pulp-ledger.tsv"; done < "$work/$family.tsv"; cmp "$work/$family.tsv" "$work/$family-pulp-ledger.tsv"
done
sed 's/Seme\.immutable_closure_run(base, value)/(function(x) return x end)(base)/' "$source" > "$work/raw.lua"
if node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/raw.lua" --module "$module" --package bad --revision 1 --entry Immutable --out "$work/bad.g1" 2> "$work/bad.log"; then echo 'raw Lua closure accepted' >&2; exit 1; fi
rg -q 'lua.unsupported_expression:.*:[1-9][0-9]*:1' "$work/bad.log"
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.lua["UAB-06"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'Lua UAB-06 complete acceptance: all five evidence classes pass'
