#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-go09.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM; GOCACHE="$work/go"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
fixture="$repo/fixtures/go-uab-09"; vectors="$fixture/vectors.json"; module="$repo/modules/execution/v20/module.g1"; native_goroot=$(GOTOOLCHAIN=local go env GOROOT)
(cd "$repo/reference/go" && go test -buildvcs=false ./goprovider ./goprojector ./canonicaleval ./wasmtarget ./cmd/effect-eval && go build -buildvcs=false -o "$work/session" ./cmd/go-session-proof && go build -buildvcs=false -o "$work/projector" ./cmd/go-projector && go build -buildvcs=false -o "$work/eval" ./cmd/effect-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
(cd "$fixture" && GOROOT="$native_goroot" go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/native.json")
GOROOT="$native_goroot" "$work/session" --module "$module" --project "$fixture" --package example.test/go-uab-09 --entry Observe --revision 1 --out "$work/source.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"
"$work/projector" -package effects "$work/source.g1" "$work/projected.go"; mkdir -p "$work/projected/cmd/native-observations"; cp "$fixture/go.mod" "$work/projected/go.mod"; cp "$work/projected.go" "$work/projected/program.go"; cp "$fixture/cmd/native-observations/main.go" "$work/projected/cmd/native-observations/main.go"; (cd "$work/projected" && GOROOT="$native_goroot" go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/projected.json"); node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
GOROOT="$native_goroot" "$work/session" --module "$module" --project "$work/projected" --package example.test/go-uab-09 --entry Observe --revision 1 --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"
node "$repo/reference/js/go-uab-09-vectors.mjs" "$vectors" --canonical > "$work/canonical-vectors.json"; "$work/eval" "$work/program.seme" "$work/canonical-vectors.json" > "$work/canonical.json"; node -e 'const fs=require("fs"),u=require("util"),n=JSON.parse(fs.readFileSync(process.argv[1])).valid,c=JSON.parse(fs.readFileSync(process.argv[2])).valid;if(!u.isDeepStrictEqual(n,c))process.exit(1)' "$work/native.json" "$work/canonical.json"
"$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"; rg -q '"observability.log"' "$work/abi.json"; node "$repo/reference/js/go-uab-09-vectors.mjs" "$vectors" > "$work/requests.tsv"; : > "$work/wasm-ledger.tsv"; tab=$(printf '\t'); while IFS="$tab" read -r kind name request response trace; do [ "$request" = - ] && request=; if [ "$kind" = valid ]; then node "$repo/reference/js/pure-function-effect-runner.mjs" "$work/program.wasm" "$request" "$response" "$trace" granted >/dev/null; else if node "$repo/reference/js/pure-function-effect-runner.mjs" "$work/program.wasm" "$request" "" "" granted >/dev/null 2>&1; then exit 1; fi; fi; printf '%s\t%s\n' "$kind" "$name" >> "$work/wasm-ledger.tsv"; done < "$work/requests.tsv"; node -e 'const fs=require("fs"),a=fs.readFileSync(process.argv[1],"utf8").trim().split("\n").map(x=>x.split("\t").slice(0,2).join("\t")),b=fs.readFileSync(process.argv[2],"utf8").trim().split("\n");require("assert").deepStrictEqual(a,b)' "$work/requests.tsv" "$work/wasm-ledger.tsv"
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$commit^{commit}"; mkdir "$work/pinned" "$work/pulp"; git -C "$pulp_repo" archive "$commit" | tar -x -C "$work/pinned"; cp "$repo/targets/wasm/pulp-effect-v1/capability.go" "$work/pinned/cmd/pulp-seme-function-proof/capability.go"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/run" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-effect-v1/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$repo/targets/wasm/pulp-effect-v1/pulp.denied.cell.toml" "$work/pulp/pulp.denied.cell.toml"; cp "$work/program.wasm" "$work/pulp/effect-function.wasm"
: > "$work/pulp-ledger.tsv"; while IFS="$tab" read -r kind name request response trace; do [ "$kind" = valid ] || continue; (cd "$work/pulp" && "$work/run" -manifest pulp.cell.toml -provider seme.function-v1 -request "$request") > "$work/$name.log" 2>&1; rg -q "\"response\":\"$response\"" "$work/$name.log"; test "$(rg -c '^\[observability.log\]' "$work/$name.log")" -eq 2; first=$(printf '%s' "$trace"|cut -d, -f1); second=$(printf '%s' "$trace"|cut -d, -f2); rg '^\[observability.log\]' "$work/$name.log"|sed -n '1p'|rg -q "value=$first"; rg '^\[observability.log\]' "$work/$name.log"|sed -n '2p'|rg -q "value=$second"; if (cd "$work/pulp" && "$work/run" -manifest pulp.denied.cell.toml -provider seme.function-v1 -request "$request") > "$work/denied-$name.log" 2>&1; then exit 1; fi; if rg -q '^\[observability.log\]' "$work/denied-$name.log"; then exit 1; fi; printf 'valid\t%s\n' "$name" >> "$work/pulp-ledger.tsv"; done < "$work/requests.tsv"
node -e 'const fs=require("fs"),a=fs.readFileSync(process.argv[1],"utf8").trim().split("\n").filter(x=>x.startsWith("valid\t")).map(x=>x.split("\t").slice(0,2).join("\t")),b=fs.readFileSync(process.argv[2],"utf8").trim().split("\n");require("assert").deepStrictEqual(a,b)' "$work/requests.tsv" "$work/pulp-ledger.tsv"
cp -R "$fixture" "$work/source-reject"; sed -i 's/log.Print(first)/log.Println(first)/' "$work/source-reject/program.go"; if GOROOT="$native_goroot" "$work/session" --module "$module" --project "$work/source-reject" --package bad --entry Observe --revision 1 --out "$work/bad.g1" 2> "$work/bad.log"; then exit 1; fi; rg -q 'File:"program.go", Line:[1-9][0-9]*' "$work/bad.log"
effect=$(awk '$3 == "00000000000000000000000000000015" {print $2; exit}' "$work/source.g1"); boolean=$(awk '$3 == "00000000000000000000000000009020" {print $2; exit}' "$work/source.g1"); sed "s/fi 00000000000000000000000000000151 rf [0-9a-f]*/fi 00000000000000000000000000000151 rf $boolean/" "$work/source.g1" > "$work/forged.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/forged.g1" "$work/forged.seme"; if "$work/lower" "$work/forged.seme" "$work/forged.wasm" "$work/forged.json" >/dev/null 2>&1; then echo 'accepted forged effect capability' >&2; exit 1; fi
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.go["UAB-09"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'Go UAB-09 complete acceptance: all five evidence classes pass'
