#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); fixture="$repo/fixtures/lua-upb02-modules"; work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb02-graph.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/discover" ./cmd/project-source-discover && go build -buildvcs=false -o "$work/assemble" ./cmd/project-assemble && go build -buildvcs=false -o "$work/inventory" ./cmd/source-inventory-emit && go build -buildvcs=false -o "$work/detail" ./cmd/package-detail-emit && go build -buildvcs=false -o "$work/compose" ./cmd/project-v3-compose && go build -buildvcs=false -o "$work/report" ./cmd/project-v3-report)
node --test "$repo/reference/lua/lua-project-graph.test.mjs"
build(){ source=$1; destination=$2; mkdir "$destination"; node "$repo/reference/lua/lua-provider-cli.mjs" --source "$source/application.lua" --source "$source/math/sum.lua" --module "$repo/modules/execution/v35/module.g1" --package example.test/lua-upb02 --revision 1 --entry Run --out "$destination/execution.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$destination/execution.g1" "$destination/execution.seme"; "$work/assemble" -execution "$destination/execution.seme" -manifest "$fixture/seme-package-manifest.json" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v1/module.seme" -out "$destination/project-v1.seme"; "$work/discover" -root "$source" -identity example.test/lua-upb02 -language lua -toolchain "$(nvim --version | sed -n '1p')" -profile seme.lua-upb02/v1 -semantic-revision seme.lua-provider/upb02 -tracked-extensions .lua -generated-header '-- Code generated' -out "$destination/snapshot.json"; "$work/inventory" -snapshot "$destination/snapshot.json" -project "$destination/project-v1.seme" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v2/module.seme" -out "$destination/inventory-v2.seme"; (cd "$source" && node "$repo/reference/lua/lua-project-graph-cli.mjs" --files application.lua,math/sum.lua --snapshot "$destination/snapshot.json" --canonical-g1 "$destination/execution.g1" --project example.test/lua-upb02 --root-module application.lua --out "$destination/package-graph.json"); "$work/detail" -base "$destination/project-v1.seme" -inventory "$destination/inventory-v2.seme" -graph "$destination/package-graph.json" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v2/module.seme" -out "$destination/package-v2.seme"; "$work/compose" -execution-contract "$repo/modules/execution/v35/module.seme" -package-v1 "$repo/modules/package/v1/module.seme" -package-v2 "$repo/modules/package/v2/module.seme" -project-v2 "$repo/modules/project/v2/module.seme" -project-v3 "$repo/modules/project/v3/module.seme" -project "$destination/project-v1.seme" -inventory "$destination/inventory-v2.seme" -package-graph "$destination/package-v2.seme" -out "$destination/project-v3.seme"; }
build "$fixture" "$work/a"; build "$fixture" "$work/b"; for file in execution.g1 execution.seme project-v1.seme snapshot.json inventory-v2.seme package-graph.json package-v2.seme project-v3.seme;do cmp "$work/a/$file" "$work/b/$file";done
"$work/report" --execution "$repo/modules/execution/v35/module.seme" --package-v1 "$repo/modules/package/v1/module.seme" --package-v2 "$repo/modules/package/v2/module.seme" --project-v2-contract "$repo/modules/project/v2/module.seme" --project-v3-contract "$repo/modules/project/v3/module.seme" --project "$work/a/project-v1.seme" --inventory "$work/a/inventory-v2.seme" --package-graph "$work/a/package-v2.seme" --composed "$work/a/project-v3.seme" > "$work/report.json"
rg -q '"Visibility":"public"' "$work/report.json"; rg -q '"Visibility":"package"' "$work/report.json"; rg -q '"Requested":"math.sum"' "$work/report.json"; rg -q '"Alias":"Sum"' "$work/report.json"
node "$repo/reference/lua/lua-module-projector-cli.mjs" "$work/a/execution.g1" "$work/a/package-graph.json" "$work/projected"
node "$repo/reference/js/javascript-uab-01-vectors.mjs" > "$work/vectors.json"
env XDG_DATA_HOME="$work/native-data" XDG_STATE_HOME="$work/native-state" XDG_CACHE_HOME="$work/native-cache" nvim --clean -u NONE -n --headless -l "$repo/reference/lua/lua-module-native-runner.lua" "$fixture" "$work/vectors.json" "$repo/reference/lua/seme-values.lua" > "$work/native.json"
env XDG_DATA_HOME="$work/projected-data" XDG_STATE_HOME="$work/projected-state" XDG_CACHE_HOME="$work/projected-cache" nvim --clean -u NONE -n --headless -l "$repo/reference/lua/lua-module-native-runner.lua" "$work/projected" "$work/vectors.json" "$repo/reference/lua/seme-values.lua" > "$work/projected.json"
node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/projected/application.lua" --source "$work/projected/math/sum.lua" --module "$repo/modules/execution/v35/module.g1" --package example.test/lua-upb02 --revision 1 --entry Run --out "$work/relift.g1"; cmp "$work/a/execution.g1" "$work/relift.g1"
build "$work/projected" "$work/projected-a"; build "$work/projected" "$work/projected-b"; cmp "$work/projected-a/project-v3.seme" "$work/projected-b/project-v3.seme"
if build "$fixture" "$work/a" >"$work/collision.out" 2>"$work/collision.err";then exit 1;fi; test -s "$work/a/project-v3.seme"
echo 'Lua UPB-02 graph foundation: native modules, deterministic Package-v2 and Project-v3 authority pass'
