#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd);fixture="$repo/fixtures/lua-upb05-configuration";vectors="$fixture/vectors.json";pulp_repo=${PULP_REPO:-"$repo/../Pulp"};commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001;work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb05-parity.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM;GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$fixture/application.lua" --source "$fixture/configuration.lua" --source "$fixture/policy.lua" --source "$fixture/state.lua" --module "$repo/modules/execution/v36/module.g1" --package example.test/lua-upb05 --revision 1 --entry Run --out "$work/program.g1";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/program.g1" "$work/program.seme"
env XDG_DATA_HOME="$work/native-data" XDG_STATE_HOME="$work/native-state" XDG_CACHE_HOME="$work/native-cache" nvim --clean -u NONE -n --headless -l "$repo/reference/lua/lua-upb05-native-runner.lua" "$fixture" "$vectors" "$repo/reference/lua/seme-values.lua" > "$work/native.json"
(cd "$repo/reference/go"&&go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval&&go build -buildvcs=false -o "$work/codec" ./cmd/pure-application-codec&&GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -buildvcs=false -o "$work/canonical-vm.wasm" ./cmd/canonical-wasm-cell);"$work/eval" "$work/program.seme" "$vectors" --named-rejections > "$work/canonical.json";node -e 'const f=require("fs"),u=require("util"),n=JSON.parse(f.readFileSync(process.argv[1])),c=JSON.parse(f.readFileSync(process.argv[2])),v=Object.fromEntries(Object.entries(c.valid).map(([k,x])=>[k,x.i64]));if(!u.isDeepStrictEqual(n.valid,v)||JSON.stringify(Object.keys(n.rejected).sort())!==JSON.stringify(Object.keys(c.rejected).sort()))process.exit(1)' "$work/native.json" "$work/canonical.json"
node "$repo/reference/lua/lua-upb05-vectors.mjs" requests "$vectors" > "$work/requests.jsonl";node "$repo/reference/lua/lua-upb05-vectors.mjs" expected "$vectors" > "$work/expected.jsonl";"$work/codec" encode "$work/program.seme" < "$work/requests.jsonl" > "$work/requests.hex";node "$repo/reference/js/canonical-wasm-cell-runner.mjs" "$work/canonical-vm.wasm" "$work/program.seme" "$work/requests.hex" > "$work/wasm.hex";"$work/codec" observe "$work/program.seme" < "$work/wasm.hex" > "$work/wasm.jsonl";cmp "$work/expected.jsonl" "$work/wasm.jsonl"
test -f "$pulp_repo/go.mod";git -C "$pulp_repo" cat-file -e "$commit^{commit}";mkdir "$work/pinned" "$work/pulp";git -C "$pulp_repo" archive "$commit"|tar -x -C "$work/pinned";(cd "$work/pinned"&&mkdir -p cmd/pulp-seme-canonical-vm-proof&&cp "$repo/targets/wasm/pulp-canonical-vm-v1/runner.go" cmd/pulp-seme-canonical-vm-proof/main.go&&go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-canonical-vm-proof);cp "$repo/targets/wasm/pulp-canonical-vm-v1/pulp.cell.toml" "$work/pulp/pulp.cell.toml";cp "$work/canonical-vm.wasm" "$work/pulp/canonical-vm.wasm";"$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -graph "$work/program.seme" -requests "$work/requests.hex" > "$work/pulp.raw.jsonl";node "$repo/reference/js/pulp-canonical-vm-output.mjs" "$work/pulp.raw.jsonl" > "$work/pulp.hex";"$work/codec" observe "$work/program.seme" < "$work/pulp.hex" > "$work/pulp.jsonl";cmp "$work/expected.jsonl" "$work/pulp.jsonl"
echo 'Lua UPB-05 parity: native, canonical, Wasm, and pinned Pulp agree'
