#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; work=$(mktemp -d /tmp/go03.XXXX); trap 'rm -rf "$work"' EXIT
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/xdg-cache"; export GOCACHE XDG_CACHE_HOME; vectors="$repo/fixtures/go-uab-03/vectors.json"
(cd "$repo/reference/go" && go test ./goprovider ./goprojector ./canonicaleval ./wasmtarget && go build -o "$work/session" ./cmd/go-session-proof && go build -o "$work/projector" ./cmd/go-projector && go build -o "$work/eval" ./cmd/canonical-eval && go build -o "$work/lower" ./cmd/pure-wasm-lower)
(cd "$repo/fixtures/go-uab-03" && go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/native.json")
"$work/session" --module "$repo/modules/execution/v32/module.g1" --project "$repo/fixtures/go-uab-03" --package example.test/go-uab-03 --entry Execute --revision 1 --out "$work/source.g1"
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"; "$work/eval" "$work/program.seme" "$vectors" > "$work/canonical.json"; "$work/projector" -package control "$work/source.g1" "$work/projected.go"
mkdir -p "$work/projected/cmd/native-observations"; cp "$repo/fixtures/go-uab-03/go.mod" "$work/projected/go.mod"; cp "$work/projected.go" "$work/projected/program.go"; cp "$repo/fixtures/go-uab-03/cmd/native-observations/main.go" "$work/projected/cmd/native-observations/main.go"; (cd "$work/projected" && go run -buildvcs=false ./cmd/native-observations "$vectors" > "$work/projected.json")
"$work/session" --module "$repo/modules/execution/v32/module.g1" --project "$work/projected" --package example.test/go-uab-03 --entry Execute --revision 1 --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"; "$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"
node "$repo/reference/js/go-uab-03-wasm-runner.mjs" "$work/program.wasm" "$vectors" > "$work/wasm.json"; node "$repo/reference/js/go-uab-03-wasm-runner.mjs" "$work/program.wasm" "$vectors" --tsv > "$work/vectors.tsv"
mkdir "$work/pulp" "$work/pinned"; git -C "$pulp_repo" archive acc66ca61fe69c5f2c4093bc55e13aeac6dcc001 | tar -x -C "$work/pinned"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$work/program.wasm" "$work/pulp/pure-function.wasm"; : > "$work/pulp.log"
while IFS="$(printf '\t')" read -r kind name request response; do if [ "$kind" = valid ]; then "$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -provider seme.function-v2 -request "$request" >> "$work/pulp.log"; elif "$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -provider seme.function-v2 -request "$request" >/dev/null 2>&1; then exit 1; fi; done < "$work/vectors.tsv"
node "$repo/reference/js/pulp-control-normalize.mjs" "$vectors" "$work/pulp.log" > "$work/pulp.json"; node "$repo/reference/js/control-observation-compare.mjs" "$vectors" "$work/native.json" "$work/projected.json" "$work/canonical.json" "$work/wasm.json" "$work/pulp.json"
if "$work/session" --module "$repo/modules/execution/v32/module.g1" --project "$repo/fixtures/go-uab-03-reject" --package example.test/go-uab-03-reject --entry Unsupported --revision 1 --out "$work/no.g1" 2> "$work/reject"; then exit 1; fi; rg -q control.unsupported_statement "$work/reject"
node -e 'const r=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];if(JSON.stringify(r.languages.go["UAB-03"])!==JSON.stringify(e))process.exit(1)' "$repo/conformance/uab-v1/scorecard.json"
echo 'Go UAB-03 complete acceptance: all five evidence classes pass'
