#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001; work=$(mktemp -d "${TMPDIR:-/tmp}/js08.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME; source="$repo/fixtures/javascript-uab-08/program.js"; vectors="$repo/fixtures/javascript-uab-08/vectors.json"; module="$repo/modules/execution/v32/module.g1"
node "$repo/reference/js/javascript-provider-cli.mjs" --source "$source" --module "$module" --package example.test/javascript-uab-08 --revision 1 --entry IncrementPositive --out "$work/source.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"
node "$repo/reference/js/javascript-projector-cli.mjs" "$work/source.g1" "$work/projected.js"; node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/projected.js" --module "$module" --package example.test/javascript-uab-08 --revision 1 --entry IncrementPositive --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"
node "$repo/reference/js/javascript-uab-08-native-runner.mjs" "$source" "$vectors" > "$work/original.json"; node "$repo/reference/js/javascript-uab-08-native-runner.mjs" "$work/projected.js" "$vectors" > "$work/projected.json"
(cd "$repo/reference/go" && go test -buildvcs=false ./canonicaleval ./wasmtarget && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
node "$repo/reference/js/javascript-uab-08-vectors.mjs" "$vectors" > "$work/canonical-vectors.json"; "$work/eval" "$work/program.seme" "$work/canonical-vectors.json" --named-rejections > "$work/canonical.json"; "$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"; node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/program.wasm" "$vectors" > "$work/wasm.json"
node -e 'const f=require("fs"),u=require("util"),o=JSON.parse(f.readFileSync(process.argv[1])).valid,p=JSON.parse(f.readFileSync(process.argv[2])).valid,c=JSON.parse(f.readFileSync(process.argv[3])),w=JSON.parse(f.readFileSync(process.argv[4])),cv=Object.fromEntries(Object.entries(c.valid).map(([k,x])=>[k,{variant:x.variant,payload:x.payload.i64}]));if(!u.isDeepStrictEqual(o,p)||!u.isDeepStrictEqual(o,cv)||!u.isDeepStrictEqual(o,w.valid)||JSON.stringify(Object.keys(c.rejected).sort())!==JSON.stringify(["arity","wrong-type"])||JSON.stringify(w.malformed)!==JSON.stringify(["empty","short","long"]))process.exit(1)' "$work/original.json" "$work/projected.json" "$work/canonical.json" "$work/wasm.json"
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$commit^{commit}"; mkdir "$work/pinned" "$work/pulp"; git -C "$pulp_repo" archive "$commit" | tar -x -C "$work/pinned"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/run" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$work/program.wasm" "$work/pulp/pure-function.wasm"
node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/program.wasm" "$vectors" --tsv > "$work/requests.tsv"; tab=$(printf '\t'); seen=""
while IFS="$tab" read -r kind name request response; do seen="$seen $kind:$name"; if [ "$kind" = valid ]; then (cd "$work/pulp" && "$work/run" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") > "$work/pulp-$name.log" 2>&1; rg -q "\"response\":\"$response\"" "$work/pulp-$name.log"; elif (cd "$work/pulp" && "$work/run" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") >/dev/null 2>&1; then exit 1; fi; done < "$work/requests.tsv"
test "$seen" = ' valid:success valid:zero-error valid:negative-error valid:success-wrap malformed:empty malformed:short malformed:long'
sed 's/(error) => Seme.error(error)/(error) => { throw new Error(error); }/' "$source" > "$work/throw.js"; if node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/throw.js" --module "$module" --package bad --revision 1 --entry IncrementPositive --out "$work/bad.g1" 2> "$work/bad.log"; then exit 1; fi; rg -q 'javascript\..*:[0-9][0-9]*:[0-9][0-9]*' "$work/bad.log"
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.javascript["UAB-08"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'JavaScript UAB-08 complete acceptance: all five evidence classes pass'
