#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd);fixture="$repo/fixtures/javascript-upb05-configuration";project=example.test/javascript-upb05
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb06.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM;GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
JS_UPB05_EXPORT="$work/base-a" "$repo/scripts/check-javascript-upb-05-foundation.sh"
(cd "$repo/reference/go"&&go build -buildvcs=false -o "$work/compose" ./cmd/project-v9-compose&&go build -buildvcs=false -o "$work/publish" ./cmd/project-roundtrip-publish&&go build -buildvcs=false -o "$work/report" ./cmd/resource-report)
compose(){ root=$1;base=$2;out=$3;"$work/compose" -root "$root" -snapshot "$base/snapshot.json" -bundle "$base/bundle" -configuration-selection "$root/configuration-selection.json" -resource-selection "$root/resources.json" -owner-package "$project/application" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-v8-contract "$repo/modules/project/v8/module.seme" -resource-contract "$repo/modules/resource/v1/module.seme" -project-v9-contract "$repo/modules/project/v9/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$out";}
compose "$fixture" "$work/base-a" "$work/v9-a";compose "$fixture" "$work/base-a" "$work/v9-b";diff -ru "$work/v9-a" "$work/v9-b"
test "$(sha256sum "$work/v9-a/blobs/247632bca93a2c19ec3212589dea38aa5a681ae910abdba4c8dce9b054c518ca"|cut -d ' ' -f 1)" = 247632bca93a2c19ec3212589dea38aa5a681ae910abdba4c8dce9b054c518ca
test "$(sha256sum "$work/v9-a/blobs/8a9796d8ef50b6b34bf659586a0926cb45caf59c4c77cb5635bf85940ca105fc"|cut -d ' ' -f 1)" = 8a9796d8ef50b6b34bf659586a0926cb45caf59c4c77cb5635bf85940ca105fc
node "$repo/reference/js/javascript-module-projector-cli.mjs" "$work/base-a/bundle/construction-v36.g1" "$work/base-a/graph.json" "$work/modules"
"$work/publish" -root "$fixture" -snapshot "$work/base-a/snapshot.json" -dest "$work/projected" -projected "application.js=$work/modules/application.js" -projected "configuration.js=$work/modules/configuration.js" -projected "policy.js=$work/modules/policy.js" -tracked-extensions .js -generated-header '// Code generated'
for file in resources.json resources/notice.txt resources/marker.bin package.json package-lock.json configuration-selection.json;do cmp "$fixture/$file" "$work/projected/$file";done
JS_UPB_FIXTURE="$work/projected" JS_UPB_PROJECT="$project" JS_UPB05_EXPORT="$work/base-projected" "$repo/scripts/check-javascript-upb-05-foundation.sh"
compose "$work/projected" "$work/base-projected" "$work/v9-projected";cmp "$work/base-a/bundle/construction-v36.g1" "$work/base-projected/bundle/construction-v36.g1";diff -ru "$work/v9-a/blobs" "$work/v9-projected/blobs";"$work/report" "$work/v9-a/resource-v1.seme" > "$work/report-a.json";"$work/report" "$work/v9-projected/resource-v1.seme" > "$work/report-projected.json";cmp "$work/report-a.json" "$work/report-projected.json"
if compose "$fixture" "$work/base-a" "$work/v9-a" > "$work/collision.out" 2> "$work/collision.err";then exit 1;fi;test ! -s "$work/collision.out"
cp -R "$fixture" "$work/changed";printf x >> "$work/changed/resources/marker.bin";if compose "$work/changed" "$work/base-a" "$work/reject-changed" > "$work/changed.out" 2> "$work/changed.err";then exit 1;fi;test ! -e "$work/reject-changed";test ! -s "$work/changed.out"
echo 'JavaScript UPB-06 foundation: detached resources and Project-v9 authority reproduce'
