#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd);fixture="$repo/fixtures/javascript-upb05-configuration";work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb09.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM;GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
JS_UPB08_EXPORT="$work/prior" "$repo/scripts/check-javascript-upb-08-foundation.sh"
"$repo/scripts/check-controlled-effects-v1.sh";"$repo/scripts/check-project-contract-v12.sh"
(cd "$repo/reference/go"&&go test -p=1 -count=1 ./gocontrolledeffectsmanifest ./gocontrolledeffectsadapter ./controlledeffectsinstance ./projectv12instance ./cmd/project-v12-compose&&go build -buildvcs=false -o "$work/compose" ./cmd/project-v12-compose)
bundle="$work/bundle-v11";mkdir "$bundle" "$bundle/blobs"
v8="$work/prior/prior/prior/base/bundle";v9="$work/prior/prior/prior/v9";v10="$work/prior/prior/v10";v11="$work/prior/v11"
for f in construction-v36.g1 execution-v36.seme project-base-v8.seme inventory-v8.seme package-detail-v4.seme package-v4.seme dependency-v1.seme configuration-v3.seme project-v8.seme;do cp "$v8/$f" "$bundle/$f";done
for f in resource-v1.seme project-v9.seme;do cp "$v9/$f" "$bundle/$f";done;cp -R "$v9/blobs/." "$bundle/blobs"
for f in durable-state-v1.seme source-presentation-v1.seme project-v10.seme;do cp "$v10/$f" "$bundle/$f";done
for f in ordered-transport-v1.seme project-v11.seme;do cp "$v11/$f" "$bundle/$f";done
printf 'seme-go-upb08-bundle-v1\n' > "$bundle/COMPLETE.sha256";for f in construction-v36.g1 execution-v36.seme project-base-v8.seme inventory-v8.seme package-detail-v4.seme package-v4.seme dependency-v1.seme configuration-v3.seme project-v8.seme resource-v1.seme project-v9.seme durable-state-v1.seme source-presentation-v1.seme project-v10.seme ordered-transport-v1.seme project-v11.seme;do printf '%s %s\n' "$f" "$(sha256sum "$bundle/$f"|cut -d ' ' -f 1)" >> "$bundle/COMPLETE.sha256";done;for p in "$bundle"/blobs/*;do h=$(basename "$p");printf 'blobs/%s %s\n' "$h" "$h" >> "$bundle/COMPLETE.sha256";done
compose(){ selection=$1;out=$2;input=${3:-"$bundle"};"$work/compose" -bundle-v11 "$input" -configuration-selection "$fixture/configuration-selection.json" -durable-selection "$fixture/durable-selection.json" -transport-selection "$fixture/transport-selection.json" -effects-selection "$selection" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -resource-contract "$repo/modules/resource/v1/module.seme" -durable-state-contract "$repo/modules/durable-state/v1/module.seme" -source-presentation-contract "$repo/modules/source-presentation/v1/module.seme" -ordered-transport-contract "$repo/modules/ordered-transport/v1/module.seme" -controlled-effects-contract "$repo/modules/controlled-effects/v1/module.seme" -project-v8-contract "$repo/modules/project/v8/module.seme" -project-v9-contract "$repo/modules/project/v9/module.seme" -project-v10-contract "$repo/modules/project/v10/module.seme" -project-v11-contract "$repo/modules/project/v11/module.seme" -project-v12-contract "$repo/modules/project/v12/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$out";}
compose "$fixture/controlled-effects-selection.json" "$work/v12-a";compose "$fixture/controlled-effects-selection.json" "$work/v12-b";diff -ru "$work/v12-a" "$work/v12-b";test -s "$work/v12-a/controlled-effects-v1.seme";test -s "$work/v12-a/project-v12.seme";test -s "$work/v12-a/controlled-replay-v1.json"
reject(){ name=$1;selection=$2;input=${3:-"$bundle"};if compose "$selection" "$work/reject-$name" "$input" >"$work/$name.out" 2>"$work/$name.err";then echo "JavaScript UPB-09 accepted $name" >&2;exit 1;fi;test ! -e "$work/reject-$name";test ! -s "$work/$name.out";}
if compose "$fixture/controlled-effects-selection.json" "$work/v12-a" >"$work/collision.out" 2>"$work/collision.err";then exit 1;fi;test ! -s "$work/collision.out"
for kind in owner next replay policy bounds unknown;do node - "$fixture/controlled-effects-selection.json" "$work/$kind.json" "$kind" <<'NODE'
const fs=require("fs"),d=JSON.parse(fs.readFileSync(process.argv[2])),k=process.argv[4];if(k==="owner")d.clock.owner="missing";if(k==="next")d.random.next.name="Missing";if(k==="replay")d.application.replay=d.application.dispatch;if(k==="policy")d.random.algorithm="Math.random";if(k==="bounds")d.bounds.maximum_steps=0;if(k==="unknown")d.clock.provider="Date.now";fs.writeFileSync(process.argv[3],JSON.stringify(d));
NODE
reject "$kind" "$work/$kind.json";done
cp -R "$bundle" "$work/stale";printf x >> "$work/stale/project-v11.seme";reject stale "$fixture/controlled-effects-selection.json" "$work/stale"
if test -n "${JS_UPB09_EXPORT:-}";then test ! -e "$JS_UPB09_EXPORT";mkdir "$JS_UPB09_EXPORT";cp -R "$work/prior" "$JS_UPB09_EXPORT/prior";cp -R "$bundle" "$JS_UPB09_EXPORT/v11-bundle";cp -R "$work/v12-a" "$JS_UPB09_EXPORT/v12";fi
echo 'JavaScript UPB-09 foundation: Controlled-Effects-v1 and Project-v12 authorities reproduce'
