#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; pulp_commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-js07-full.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM; GOCACHE="$work/go"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
source="$repo/fixtures/javascript-uab-07/program.js"; vectors="$repo/fixtures/javascript-uab-07/vectors.json"; module="$repo/modules/execution/v27/module.g1"
node "$repo/reference/js/javascript-provider-cli.mjs" --source "$source" --module "$module" --package example.test/javascript-uab-07 --revision 1 --entry Step --out "$work/source.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/source.g1" "$work/program.seme"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/kernel-wire-validator.k0" "$work/program.seme"
node "$repo/reference/js/javascript-projector-cli.mjs" "$work/source.g1" "$work/projected.js"; node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/projected.js" --module "$module" --package example.test/javascript-uab-07 --revision 1 --entry Step --out "$work/relift.g1"; cmp "$work/source.g1" "$work/relift.g1"
node "$repo/reference/js/javascript-uab-07-native-runner.mjs" "$source" "$vectors" > "$work/native.json"; node "$repo/reference/js/javascript-uab-07-native-runner.mjs" "$work/projected.js" "$vectors" > "$work/projected.json"; node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
(cd "$repo/reference/go" && go test -buildvcs=false ./canonicaleval ./wasmtarget && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
node "$repo/reference/js/javascript-uab-07-vectors.mjs" "$vectors" > "$work/canonical-vectors.json"; "$work/eval" "$work/program.seme" "$work/canonical-vectors.json" --named-rejections > "$work/canonical.json"; "$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"; node "$repo/reference/js/javascript-uab-07-wasm-runner.mjs" "$work/program.wasm" "$vectors" > "$work/wasm.json"
node -e 'const fs=require("fs"),u=require("util"),n=JSON.parse(fs.readFileSync(process.argv[1])).valid,c=JSON.parse(fs.readFileSync(process.argv[2])),w=JSON.parse(fs.readFileSync(process.argv[3]));const cv=Object.fromEntries(Object.entries(c.valid).map(([k,v])=>[k,{state:v.state.fields.Value.i64,result:v.result.i64}]));if(!u.isDeepStrictEqual(n,cv)||!u.isDeepStrictEqual(n,w.valid)||!u.isDeepStrictEqual(Object.keys(c.rejected).sort(),["arity","delta-is-bool","missing-record-field"])||!u.isDeepStrictEqual(w.malformed,["empty","short","long"]))process.exit(1)' "$work/native.json" "$work/canonical.json" "$work/wasm.json"
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$pulp_commit^{commit}"; mkdir "$work/pinned" "$work/pulp"; git -C "$pulp_repo" archive "$pulp_commit" | tar -x -C "$work/pinned"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$work/program.wasm" "$work/pulp/pure-function.wasm"
node "$repo/reference/js/javascript-uab-07-wasm-runner.mjs" "$work/program.wasm" "$vectors" --tsv > "$work/requests.tsv"; : > "$work/pulp-audit.tsv"; tab=$(printf '\t'); while IFS="$tab" read -r kind name request response; do if [ "$kind" = valid ]; then (cd "$work/pulp" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") > "$work/$name.log" 2>&1; rg -q "\"response\":\"$response\"" "$work/$name.log"; elif (cd "$work/pulp" && "$work/pulp-runner" -manifest pulp.cell.toml -provider seme.function-v2 -request "$request") >/dev/null 2>&1; then exit 1; fi; printf '%s\t%s\n' "$kind" "$name" >> "$work/pulp-audit.tsv"; done < "$work/requests.tsv"
node -e 'const fs=require("fs"),names=p=>fs.readFileSync(p,"utf8").trim().split("\n").map(x=>x.split("\t").slice(0,2));require("assert").deepStrictEqual(names(process.argv[1]),names(process.argv[2]))' "$work/requests.tsv" "$work/pulp-audit.tsv"
sed 's/result: counter.Value/result: state.Value/' "$source" > "$work/alias.js"; if node "$repo/reference/js/javascript-provider-cli.mjs" --source "$work/alias.js" --module "$module" --package example.test/javascript-uab-07-bad --revision 1 --entry Step --out "$work/bad.g1" 2> "$work/bad.log"; then echo 'undeclared state alias accepted' >&2; exit 1; fi; rg -q 'javascript\..*:[0-9][0-9]*:[0-9][0-9]*' "$work/bad.log"
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.javascript["UAB-07"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'JavaScript UAB-07 complete acceptance: all five evidence classes pass'
