#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); fixture="$repo/fixtures/lua-upb02-modules"; pulp_repo=${PULP_REPO:-"$repo/../Pulp"}; pulp_commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001; work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb02-parity.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$fixture/application.lua" --source "$fixture/math/sum.lua" --module "$repo/modules/execution/v35/module.g1" --package example.test/lua-upb02 --revision 1 --entry Run --out "$work/execution.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/execution.g1" "$work/execution.seme"
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval && go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower)
node "$repo/reference/js/javascript-uab-01-vectors.mjs" > "$work/vectors.json"; env XDG_DATA_HOME="$work/native-data" XDG_STATE_HOME="$work/native-state" XDG_CACHE_HOME="$work/native-cache" nvim --clean -u NONE -n --headless -l "$repo/reference/lua/lua-module-native-runner.lua" "$fixture" "$work/vectors.json" "$repo/reference/lua/seme-values.lua" > "$work/native.json"; "$work/eval" "$work/execution.seme" "$work/vectors.json" --named-rejections > "$work/canonical.json"
node -e 'const f=require("fs"),u=require("util"),n=JSON.parse(f.readFileSync(process.argv[1])),c=JSON.parse(f.readFileSync(process.argv[2])),v=Object.fromEntries(Object.entries(c.valid).map(([k,x])=>[k,x.i64]));if(!u.isDeepStrictEqual(n.valid,v)||JSON.stringify(Object.keys(c.rejected).sort())!==JSON.stringify(["wrong-arity","wrong-type"]))process.exit(1)' "$work/native.json" "$work/canonical.json"
"$work/lower" "$work/execution.seme" "$work/program.wasm" "$work/abi.json"; node "$repo/reference/js/pure-function-runner.mjs" "$work/program.wasm" 07000000000000000500000000000000 > "$work/wasm.log"; rg -q '"response":"0c00000000000000"' "$work/wasm.log"
test -f "$pulp_repo/go.mod"; git -C "$pulp_repo" cat-file -e "$pulp_commit^{commit}"; mkdir "$work/pinned" "$work/pulp"; git -C "$pulp_repo" archive "$pulp_commit" | tar -x -C "$work/pinned"; (cd "$work/pinned" && go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof); cp "$repo/targets/wasm/pulp-function-v1/pulp.cell.toml" "$work/pulp/pulp.cell.toml"; cp "$work/program.wasm" "$work/pulp/pure-function.wasm"; "$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -provider seme.function-v1 -request 07000000000000000500000000000000 > "$work/pulp.log" 2>&1; rg -q '"response":"0c00000000000000"' "$work/pulp.log"
echo 'Lua UPB-02 exact project parity: native, canonical, Wasm, and pinned Pulp agree'
