#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd);pulp_repo=${PULP_REPO:-"$repo/../Pulp"};pulp_commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-uab03.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM
XDG_CACHE_HOME="$work/cache";GOCACHE="$work/go-cache";export XDG_CACHE_HOME GOCACHE
node --test "$repo/reference/lua/lua-provider.test.mjs"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$repo/fixtures/lua-uab-03/program.lua" --module "$repo/modules/execution/v32/module.g1" --package example.test/lua-uab03 --revision 1 --entry Accumulate --out "$work/program.g1"
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/program.g1" "$work/program.seme";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/kernel-wire-validator.k0" "$work/program.seme";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/modules/foundation/v1/validator.k0" "$work/program.seme"
node "$repo/reference/lua/lua-projector-cli.mjs" "$work/program.g1" "$work/projected.lua";node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/projected.lua" --module "$repo/modules/execution/v32/module.g1" --package example.test/lua-uab03 --revision 1 --entry Accumulate --out "$work/relift.g1";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/relift.g1" "$work/relift.seme";cmp "$work/program.seme" "$work/relift.seme"
env XDG_DATA_HOME="$work/nvim-data" XDG_STATE_HOME="$work/nvim-state" XDG_CACHE_HOME="$work/nvim-cache" nvim -l "$repo/reference/lua/lua-uab-03-native.lua" "$repo/fixtures/lua-uab-03/program.lua" "$repo/fixtures/lua-uab-03/vectors.json" > "$work/original.json"
env XDG_DATA_HOME="$work/nvim-data2" XDG_STATE_HOME="$work/nvim-state2" XDG_CACHE_HOME="$work/nvim-cache2" nvim -l "$repo/reference/lua/lua-uab-03-native.lua" "$work/projected.lua" "$repo/fixtures/lua-uab-03/vectors.json" > "$work/projected.json"
(cd "$repo/reference/go"&&go test -buildvcs=false ./canonicaleval ./wasmtarget&&go build -buildvcs=false -o "$work/canonical" ./cmd/canonical-eval&&go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower);node "$repo/reference/js/control-vector-adapter.mjs" canonical "$repo/fixtures/lua-uab-03/vectors.json" > "$work/canonical-vectors.json";"$work/canonical" "$work/program.seme" "$work/canonical-vectors.json" > "$work/canonical.json";"$work/lower" "$work/program.seme" "$work/program.wasm" "$work/abi.json"
node "$repo/reference/js/control-function-runner.mjs" "$work/program.wasm" "$repo/fixtures/lua-uab-03/vectors.json" > "$work/wasm.json"
mkdir "$work/pulp" "$work/pulp-pinned";git -C "$pulp_repo" archive "$pulp_commit"|tar -x -C "$work/pulp-pinned";(cd "$work/pulp-pinned"&&go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-function-proof);cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml";cp "$work/program.wasm" "$work/pulp/pure-function.wasm";set -- -manifest "$work/pulp/pulp.cell.toml" -provider seme.function-v2;for request in $(node "$repo/reference/js/control-vector-adapter.mjs" requests "$repo/fixtures/lua-uab-03/vectors.json");do set -- "$@" -request "$request";done;"$work/pulp-runner" "$@" > "$work/pulp.log";node "$repo/reference/js/control-vector-adapter.mjs" checked-requests "$repo/fixtures/lua-uab-03/vectors.json" > "$work/checked-requests";: > "$work/pulp-rejections";while read -r name request;do if "$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -provider seme.function-v2 -request "$request" > "$work/rejected.log" 2>&1;then echo "Pulp accepted hazardous request: $name" >&2;exit 1;fi;echo "$name" >> "$work/pulp-rejections";done < "$work/checked-requests";node "$repo/reference/js/control-vector-adapter.mjs" normalize-pulp "$repo/fixtures/lua-uab-03/vectors.json" "$work/pulp.log" "$work/pulp-rejections" > "$work/pulp.json"
node "$repo/reference/js/control-observation-compare.mjs" "$repo/fixtures/lua-uab-03/vectors.json" "$work/original.json" "$work/projected.json" "$work/canonical.json" "$work/wasm.json" "$work/pulp.json"
for mutation in raw-arithmetic truthiness parameter-assignment forward-local incompatible-assignment unsupported-loop multiple-return implicit-return;do case $mutation in
raw-arithmetic) sed 's/Seme.add(index, Seme.i64_literal("1"))/index + 1/' "$repo/fixtures/lua-uab-03/program.lua";;
truthiness) sed 's/Seme.boolean(enabled) and Seme.less_equal(Seme.index_zero(values, probe), limit)/limit/' "$repo/fixtures/lua-uab-03/program.lua";;
parameter-assignment) sed 's/total = Seme.add(total, index)/limit = Seme.add(total, index)/' "$repo/fixtures/lua-uab-03/program.lua";;
forward-local) sed '/local total =/i\  total = Seme.i64_literal("0")' "$repo/fixtures/lua-uab-03/program.lua";;
incompatible-assignment) sed 's/total = Seme.add(total, index)/total = Seme.boolean(enabled)/' "$repo/fixtures/lua-uab-03/program.lua";;
unsupported-loop) sed 's/while Seme.boolean(enabled) and Seme.less_equal(index, limit) do/while true do/' "$repo/fixtures/lua-uab-03/program.lua";;
multiple-return) sed '/local total =/i\  return Seme.i64_literal("0")' "$repo/fixtures/lua-uab-03/program.lua";;
implicit-return) sed '/^  return total$/d' "$repo/fixtures/lua-uab-03/program.lua";;
esac > "$work/bad.lua";if node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/bad.lua" --module "$repo/modules/execution/v32/module.g1" --package example.test/lua-uab03 --revision 1 --entry Accumulate --out "$work/bad.g1" 2> "$work/bad.log";then echo "$mutation accepted" >&2;exit 1;fi;rg -q 'lua\.' "$work/bad.log";done
node -e 'const r=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];if(JSON.stringify(r.languages.lua["UAB-03"])!==JSON.stringify(e))process.exit(1)' "$repo/conformance/uab-v1/scorecard.json"
echo "Lua UAB-03 complete acceptance: all five evidence classes pass"
