#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd);fixture="$repo/fixtures/javascript-upb05-configuration";vectors="$fixture/vectors.json";pulp_repo=${PULP_REPO:-"$repo/../Pulp"};commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb05-parity.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM;GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
(cd "$fixture"&&node "$repo/reference/js/javascript-package-provider-cli.mjs" --files application.js,configuration.js,policy.js,state.js --module "$repo/modules/execution/v36/module.g1" --package example.test/javascript-upb05 --entry Run --revision 1 --out "$work/program.g1")
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/program.g1" "$work/program.seme"
node "$repo/reference/js/javascript-upb05-native-parity.mjs" "$fixture" "$vectors" > "$work/native.json";node "$repo/reference/js/javascript-upb05-vectors.mjs" canonical "$vectors" > "$work/canonical-vectors.json"
(cd "$repo/reference/go"&&go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval&&go build -buildvcs=false -o "$work/codec" ./cmd/pure-application-codec&&GOOS=wasip1 GOARCH=wasm go build -buildmode=c-shared -buildvcs=false -o "$work/canonical-vm.wasm" ./cmd/canonical-wasm-cell)
"$work/eval" "$work/program.seme" "$work/canonical-vectors.json" > "$work/canonical.json";node -e 'const f=require("fs"),u=require("util"),a=JSON.parse(f.readFileSync(process.argv[1])).valid,b=JSON.parse(f.readFileSync(process.argv[2])).valid,x={};for(const[k,v]of Object.entries(b))x[k]=v.i64;if(!u.isDeepStrictEqual(a,x)){console.error(a,x);process.exit(1)}' "$work/native.json" "$work/canonical.json"
node "$repo/reference/js/javascript-upb05-vectors.mjs" requests "$vectors" > "$work/requests.jsonl";node "$repo/reference/js/javascript-upb05-vectors.mjs" expected "$vectors" > "$work/expected.jsonl";"$work/codec" encode "$work/program.seme" < "$work/requests.jsonl" > "$work/requests.hex";node "$repo/reference/js/canonical-wasm-cell-runner.mjs" "$work/canonical-vm.wasm" "$work/program.seme" "$work/requests.hex" > "$work/wasm.hex";"$work/codec" observe "$work/program.seme" < "$work/wasm.hex" > "$work/wasm.jsonl";cmp "$work/expected.jsonl" "$work/wasm.jsonl"
test -f "$pulp_repo/go.mod";git -C "$pulp_repo" cat-file -e "$commit^{commit}";mkdir "$work/pinned" "$work/pulp";git -C "$pulp_repo" archive "$commit"|tar -x -C "$work/pinned";(cd "$work/pinned"&&mkdir -p cmd/pulp-seme-canonical-vm-proof&&cp "$repo/targets/wasm/pulp-canonical-vm-v1/runner.go" cmd/pulp-seme-canonical-vm-proof/main.go&&go build -buildvcs=false -o "$work/pulp-runner" ./cmd/pulp-seme-canonical-vm-proof);cp "$repo/targets/wasm/pulp-canonical-vm-v1/pulp.cell.toml" "$work/pulp/pulp.cell.toml";cp "$work/canonical-vm.wasm" "$work/pulp/canonical-vm.wasm";"$work/pulp-runner" -manifest "$work/pulp/pulp.cell.toml" -graph "$work/program.seme" -requests "$work/requests.hex" > "$work/pulp.raw.jsonl";node "$repo/reference/js/pulp-canonical-vm-output.mjs" "$work/pulp.raw.jsonl" > "$work/pulp.hex";"$work/codec" observe "$work/program.seme" < "$work/pulp.hex" > "$work/pulp.jsonl";cmp "$work/expected.jsonl" "$work/pulp.jsonl"
echo 'JavaScript UPB-05 parity: native, canonical, Wasm, and pinned Pulp agree'
