#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd);pulp_repo=${PULP_REPO:-"$repo/../Pulp"};commit=acc66ca61fe69c5f2c4093bc55e13aeac6dcc001;work=$(mktemp -d "${TMPDIR:-/tmp}/lua08.XXXXXX");trap 'rm -rf "$work"' EXIT;GOCACHE="$work/go";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME;source="$repo/fixtures/lua-uab-08/program.lua";vectors="$repo/fixtures/lua-uab-08/vectors.json";module="$repo/modules/execution/v32/module.g1"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$source" --module "$module" --package example.test/lua-uab-08 --revision 1 --entry IncrementPositive --out "$work/a.g1";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/a.g1" "$work/a.seme";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/kernel-wire-validator.k0" "$work/a.seme";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/modules/foundation/v1/validator.k0" "$work/a.seme";node "$repo/reference/lua/lua-projector-cli.mjs" "$work/a.g1" "$work/projected.lua";node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/projected.lua" --module "$module" --package example.test/lua-uab-08 --revision 1 --entry IncrementPositive --out "$work/b.g1";cmp "$work/a.g1" "$work/b.g1"
env XDG_DATA_HOME="$work/d1" XDG_STATE_HOME="$work/s1" XDG_CACHE_HOME="$work/c1" nvim -l "$repo/reference/lua/lua-uab-08-native.lua" "$source" "$vectors" 2>"$work/native.json";env XDG_DATA_HOME="$work/d2" XDG_STATE_HOME="$work/s2" XDG_CACHE_HOME="$work/c2" nvim -l "$repo/reference/lua/lua-uab-08-native.lua" "$work/projected.lua" "$vectors" 2>"$work/projected.json";node "$repo/reference/js/json-equal.mjs" "$work/native.json" "$work/projected.json"
(cd "$repo/reference/go"&&go test -buildvcs=false ./canonicaleval ./wasmtarget&&go build -buildvcs=false -o "$work/eval" ./cmd/canonical-eval&&go build -buildvcs=false -o "$work/lower" ./cmd/pure-wasm-lower);node "$repo/reference/js/javascript-uab-08-vectors.mjs" "$vectors">"$work/v.json";"$work/eval" "$work/a.seme" "$work/v.json" --named-rejections>"$work/canonical.json";"$work/lower" "$work/a.seme" "$work/a.wasm" "$work/abi.json";node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/a.wasm" "$vectors">"$work/wasm.json"
node -e 'const f=require("fs"),u=require("util"),n=JSON.parse(f.readFileSync(process.argv[1])).valid,c=JSON.parse(f.readFileSync(process.argv[2])),w=JSON.parse(f.readFileSync(process.argv[3])),cv=Object.fromEntries(Object.entries(c.valid).map(([k,v])=>[k,{variant:v.variant,payload:v.payload.i64}]));if(!u.isDeepStrictEqual(n,cv)||!u.isDeepStrictEqual(n,w.valid)||!u.isDeepStrictEqual(Object.keys(c.rejected).sort(),["arity","wrong-type"])||!u.isDeepStrictEqual(w.malformed,["empty","short","long"]))process.exit(1)' "$work/native.json" "$work/canonical.json" "$work/wasm.json"
for x in constructor-type match-input;do node "$repo/reference/lua/lua-uab-08-forge.mjs" "$work/a.g1" "$work/$x.g1" "$x";"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/$x.g1" "$work/$x.seme";if "$work/lower" "$work/$x.seme" "$work/$x.wasm" "$work/$x.json">"$work/$x.log" 2>&1;then echo "accepted result forgery $x" >&2;exit 1;fi;rg -q 'wasm\.' "$work/$x.log";done
test -f "$pulp_repo/go.mod";git -C "$pulp_repo" cat-file -e "$commit^{commit}";mkdir "$work/pinned" "$work/pulp";git -C "$pulp_repo" archive "$commit"|tar -x -C "$work/pinned";(cd "$work/pinned"&&go build -buildvcs=false -o "$work/run" ./cmd/pulp-seme-function-proof);cp "$repo/targets/wasm/pulp-function-v2/pulp.cell.toml" "$work/pulp/pulp.cell.toml";cp "$work/a.wasm" "$work/pulp/pure-function.wasm";node "$repo/reference/js/javascript-uab-08-wasm-runner.mjs" "$work/a.wasm" "$vectors" --tsv>"$work/q.tsv";:>"$work/ledger.tsv";while IFS= read -r row;do k=$(printf '%s\n' "$row"|cut -f1);n=$(printf '%s\n' "$row"|cut -f2);q=$(printf '%s\n' "$row"|cut -f3);z=$(printf '%s\n' "$row"|cut -f4);if [ "$k" = valid ];then(cd "$work/pulp"&&"$work/run" -manifest pulp.cell.toml -provider seme.function-v2 -request "$q")>"$work/$n.log" 2>&1;rg -q "\"response\":\"$z\"" "$work/$n.log";elif(cd "$work/pulp"&&"$work/run" -manifest pulp.cell.toml -provider seme.function-v2 -request "$q")>/dev/null 2>&1;then exit 1;fi;printf '%s\n' "$row">>"$work/ledger.tsv";done<"$work/q.tsv";cmp "$work/q.tsv" "$work/ledger.tsv"
sed 's/Seme.increment_positive(value)/error("boom")/' "$source">"$work/bad.lua";if node "$repo/reference/lua/lua-provider-cli.mjs" --source "$work/bad.lua" --module "$module" --package bad --revision 1 --entry IncrementPositive --out "$work/bad.g1" 2>"$work/bad.log";then exit 1;fi;rg -q 'lua\..*:[1-9][0-9]*:1' "$work/bad.log"
node -e 'const s=require(process.argv[1]),e=["lift","native_parity","target_parity","projection_round_trip","rejection"];require("assert").deepStrictEqual(s.languages.lua["UAB-08"],e)' "$repo/conformance/uab-v1/scorecard.json"
echo 'Lua UAB-08 complete acceptance: all five evidence classes pass'
