#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); fixture="$repo/fixtures/lua-upb03-dependency"; external="$repo/fixtures/lua-upb03-external-checksum"; project=example.test/lua-upb03; work=$(mktemp -d "${TMPDIR:-/tmp}/seme-lua-upb03.XXXXXX"); trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && for command in project-source-discover project-assemble source-inventory-emit package-detail-emit project-v3-compose dependency-emit project-v4-compose project-roundtrip-publish;do go build -buildvcs=false -o "$work/$command" "./cmd/$command";done)
node --test "$repo/reference/lua/lua-rock-resolver.test.mjs"
node "$repo/reference/lua/lua-provider-cli.mjs" --source "$fixture/application.lua" --source "$fixture/math/sum.lua" --module "$repo/modules/execution/v35/module.g1" --package "$project" --revision 1 --entry Run --out "$work/execution.g1"; "$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/execution.g1" "$work/execution.seme"
"$work/project-assemble" -execution "$work/execution.seme" -manifest "$fixture/seme-package-manifest.json" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v1/module.seme" -out "$work/project-v1.seme"
"$work/project-source-discover" -root "$fixture" -identity "$project" -language lua -toolchain "$(nvim --version|sed -n '1p')" -profile seme.lua-upb03/v1 -semantic-revision seme.lua-provider/upb03 -tracked-extensions .lua -generated-header '-- Code generated' -out "$work/snapshot.json"
"$work/source-inventory-emit" -snapshot "$work/snapshot.json" -project "$work/project-v1.seme" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v2/module.seme" -out "$work/inventory-v2.seme"
(cd "$fixture" && node "$repo/reference/lua/lua-project-graph-cli.mjs" --files application.lua,math/sum.lua --snapshot "$work/snapshot.json" --canonical-g1 "$work/execution.g1" --project "$project" --root-module application.lua --out "$work/package-graph.json")
"$work/package-detail-emit" -base "$work/project-v1.seme" -inventory "$work/inventory-v2.seme" -graph "$work/package-graph.json" -execution-contract "$repo/modules/execution/v35/module.seme" -package-contract "$repo/modules/package/v1/module.seme" -project-contract "$repo/modules/project/v2/module.seme" -out "$work/package-v2.seme"
"$work/project-v3-compose" -execution-contract "$repo/modules/execution/v35/module.seme" -package-v1 "$repo/modules/package/v1/module.seme" -package-v2 "$repo/modules/package/v2/module.seme" -project-v2 "$repo/modules/project/v2/module.seme" -project-v3 "$repo/modules/project/v3/module.seme" -project "$work/project-v1.seme" -inventory "$work/inventory-v2.seme" -package-graph "$work/package-v2.seme" -out "$work/project-v3.seme"
resolve(){ node "$repo/reference/lua/lua-rock-resolver-cli.mjs" --rockspec "$1/seme-lua-upb03-1.0-1.rockspec" --lock "$1/seme-rock.lock.json" --local-root "$1" --local-files math/sum.lua --external-root "$external" --external-files checksum.lua,seme-checksum-1.2.3-1.rockspec --local-identity "$project/math/sum" --local-from "$project/application" --external-source file:../lua-upb03-external-checksum --out "$2"; }
resolve "$fixture" "$work/closure-a.json"; resolve "$fixture" "$work/closure-b.json"; cmp "$work/closure-a.json" "$work/closure-b.json"
for name in a b;do "$work/dependency-emit" -closure "$work/closure-$name.json" -contract "$repo/modules/dependency/v1/module.seme" -out "$work/dependency-$name.seme";done; cmp "$work/dependency-a.seme" "$work/dependency-b.seme"
compose(){ "$work/project-v4-compose" -execution-contract "$repo/modules/execution/v35/module.seme" -package-v1 "$repo/modules/package/v1/module.seme" -package-v2 "$repo/modules/package/v2/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -project-v2 "$repo/modules/project/v2/module.seme" -project-v3-contract "$repo/modules/project/v3/module.seme" -project-v4-contract "$repo/modules/project/v4/module.seme" -project-v1 "$work/project-v1.seme" -inventory-v2 "$work/inventory-v2.seme" -package-graph-v2 "$work/package-v2.seme" -project-v3 "$work/project-v3.seme" -dependency "$work/dependency-a.seme" -out "$1"; }
compose "$work/project-v4-a.seme"; compose "$work/project-v4-b.seme"; cmp "$work/project-v4-a.seme" "$work/project-v4-b.seme"; if compose "$work/project-v4-a.seme" >"$work/collision.out" 2>"$work/collision.err";then exit 1;fi; rg -q 'output_exists' "$work/collision.err"
cp "$work/dependency-a.seme" "$work/tampered.seme"; printf x >> "$work/tampered.seme"; if "$work/project-v4-compose" -execution-contract "$repo/modules/execution/v35/module.seme" -package-v1 "$repo/modules/package/v1/module.seme" -package-v2 "$repo/modules/package/v2/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -project-v2 "$repo/modules/project/v2/module.seme" -project-v3-contract "$repo/modules/project/v3/module.seme" -project-v4-contract "$repo/modules/project/v4/module.seme" -project-v1 "$work/project-v1.seme" -inventory-v2 "$work/inventory-v2.seme" -package-graph-v2 "$work/package-v2.seme" -project-v3 "$work/project-v3.seme" -dependency "$work/tampered.seme" -out "$work/rejected.seme" >"$work/tamper.out" 2>"$work/tamper.err";then exit 1;fi; test ! -e "$work/rejected.seme"
node "$repo/reference/lua/lua-module-projector-cli.mjs" "$work/execution.g1" "$work/package-graph.json" "$work/generated"; "$work/project-roundtrip-publish" -root "$fixture" -snapshot "$work/snapshot.json" -dest "$work/projected" -projected "application.lua=$work/generated/application.lua" -projected "math/sum.lua=$work/generated/math/sum.lua" -tracked-extensions .lua -generated-header '-- Code generated'
cmp "$fixture/seme-lua-upb03-1.0-1.rockspec" "$work/projected/seme-lua-upb03-1.0-1.rockspec"; cmp "$fixture/seme-rock.lock.json" "$work/projected/seme-rock.lock.json"; cmp "$fixture/seme-package-manifest.json" "$work/projected/seme-package-manifest.json"; resolve "$work/projected" "$work/projected-closure-a.json"; resolve "$work/projected" "$work/projected-closure-b.json"; cmp "$work/projected-closure-a.json" "$work/projected-closure-b.json"; rg -q '"Ecosystem": "luarocks"' "$work/projected-closure-a.json"; rg -q 'sha256-27ba680f16b0fbb0624507c9fd23dbae1bbee3b444e9558be4760de787a96806' "$work/projected-closure-a.json"
echo 'Lua UPB-03 dependency foundation: offline pinned rock closure and Project-v4 authority pass'
