#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); fixture=${JS_UPB_FIXTURE:-"$repo/fixtures/javascript-upb05-configuration"}; project=${JS_UPB_PROJECT:-example.test/javascript-upb05}
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb05.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && for command in project-source-discover project-assemble source-inventory-emit package-detail-emit package-v4-upgrade dependency-emit project-v8-compose go-upb05-configure;do go build -buildvcs=false -o "$work/$command" "./cmd/$command";done)
(cd "$fixture" && node "$repo/reference/js/javascript-package-provider-cli.mjs" --files application.js,configuration.js,policy.js --module "$repo/modules/execution/v36/module.g1" --package "$project" --entry Run --revision 1 --out "$work/construction.g1")
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/construction.g1" "$work/execution.seme"
"$work/project-source-discover" -root "$fixture" -identity "$project" -language javascript -toolchain "$(node --version)" -profile seme.javascript-upb05/v1 -semantic-revision seme.javascript-provider/uab11 -tracked-extensions .js -generated-header '// Code generated' -out "$work/snapshot.json"
(cd "$fixture" && node "$repo/reference/js/javascript-project-graph-cli.mjs" --files application.js,configuration.js,policy.js --snapshot "$work/snapshot.json" --canonical-g1 "$work/construction.g1" --project "$project" --root-module application.js --out "$work/graph.json")
node "$repo/reference/js/javascript-project-manifest-cli.mjs" --project "$project" --graph "$work/graph.json" --out "$work/manifest.json"
"$work/project-assemble" -execution "$work/execution.seme" -manifest "$work/manifest.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/project-base.seme"
"$work/source-inventory-emit" -snapshot "$work/snapshot.json" -project "$work/project-base.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/inventory.seme"
"$work/package-detail-emit" -base "$work/project-base.seme" -inventory "$work/inventory.seme" -graph "$work/graph.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v2.seme"
"$work/package-v4-upgrade" -package "$work/package-v2.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v4.seme"
node "$repo/reference/js/javascript-npm-resolver-cli.mjs" --manifest "$fixture/package.json" --lock "$fixture/package-lock.json" --local-root "$fixture" --local-files configuration.js,policy.js --external-root "$repo/fixtures/javascript-upb03-external-checksum" --external-files index.js,package.json --local-identity "$project/configuration" --local-from "$project/application" --external-source file:../javascript-upb03-external-checksum --out "$work/closure.json"
"$work/dependency-emit" -closure "$work/closure.json" -contract "$repo/modules/dependency/v1/module.seme" -out "$work/dependency.seme"
compose(){ destination=$1;package=${2:-"$work/package-v4.seme"};selection=${3:-"$fixture/configuration-selection.json"};"$work/project-v8-compose" -construction "$work/construction.g1" -project-base "$work/project-base.seme" -inventory "$work/inventory.seme" -package-v2 "$work/package-v2.seme" -package-v4 "$package" -dependency "$work/dependency.seme" -selection "$selection" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$destination";}
compose "$work/v8-a";compose "$work/v8-b";cmp "$work/v8-a/configuration-v3.seme" "$work/v8-b/configuration-v3.seme";cmp "$work/v8-a/project-v8.seme" "$work/v8-b/project-v8.seme"
mkdir "$work/bundle";cp "$work/construction.g1" "$work/bundle/construction-v36.g1";cp "$work/execution.seme" "$work/bundle/execution-v36.seme";cp "$work/project-base.seme" "$work/bundle/project-base-v8.seme";cp "$work/inventory.seme" "$work/bundle/inventory-v8.seme";cp "$work/package-v2.seme" "$work/bundle/package-detail-v4.seme";cp "$work/package-v4.seme" "$work/bundle/package-v4.seme";cp "$work/dependency.seme" "$work/bundle/dependency-v1.seme";cp "$work/v8-a/configuration-v3.seme" "$work/bundle/configuration-v3.seme";cp "$work/v8-a/project-v8.seme" "$work/bundle/project-v8.seme"
printf 'seme-go-upb05-bundle-v2\n' > "$work/bundle/COMPLETE.sha256";for name in construction-v36.g1 execution-v36.seme project-base-v8.seme inventory-v8.seme package-detail-v4.seme package-v4.seme dependency-v1.seme configuration-v3.seme project-v8.seme;do printf '%s %s\n' "$name" "$(sha256sum "$work/bundle/$name"|cut -d ' ' -f 1)" >> "$work/bundle/COMPLETE.sha256";done
printf '%s\n' '{"configuration_inputs":{},"runtime_inputs":{},"capability_grants":[]}' | "$work/go-upb05-configure" -bundle "$work/bundle" -selection "$fixture/configuration-selection.json" -foundation "$repo/modules/foundation/v1/module.seme" -execution "$repo/modules/execution/v36/module.seme" -package "$repo/modules/package/v4/module.seme" -dependency "$repo/modules/dependency/v1/module.seme" -configuration "$repo/modules/configuration/v3/module.seme" -project "$repo/modules/project/v8/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" > "$work/executed.json"
node -e 'const r=JSON.parse(require("fs").readFileSync(process.argv[1]));if(r.execution.outputs.length!==3||r.execution.lifecycle.length!==6)throw Error("lifecycle");const x=r.execution.outputs[2].result;if(x.kind!=="result"||x.variant!=="ok"||x.payload.fields.Ready.bool!==true||x.payload.fields.Total.i64!=="16"||x.payload.fields.Namespace.text!=="seme")throw Error("result")' "$work/executed.json"
node "$repo/reference/js/javascript-upb05-native-runner.mjs" "$fixture" > "$work/native.json"
node "$repo/reference/js/javascript-module-projector-cli.mjs" "$work/construction.g1" "$work/graph.json" "$work/projected"
(cd "$work/projected" && node "$repo/reference/js/javascript-package-provider-cli.mjs" --files application.js,configuration.js,policy.js --module "$repo/modules/execution/v36/module.g1" --package "$project" --entry Run --revision 1 --out "$work/relift.g1")
cmp "$work/construction.g1" "$work/relift.g1";node "$repo/reference/js/javascript-upb05-native-runner.mjs" "$work/projected" > "$work/projected-native.json";cmp "$work/native.json" "$work/projected-native.json"
# Equivalent source enumeration reproduces; ambient authority, stale artifacts,
# invalid lifecycle edges, and output collisions reject without publication.
(cd "$fixture"&&node "$repo/reference/js/javascript-package-provider-cli.mjs" --files policy.js,configuration.js,application.js --module "$repo/modules/execution/v36/module.g1" --package "$project" --entry Run --revision 1 --out "$work/reordered.g1");cmp "$work/construction.g1" "$work/reordered.g1"
if compose "$work/v8-a" > "$work/collision.out" 2> "$work/collision.err";then exit 1;fi;test ! -s "$work/collision.out"
cp "$work/package-v4.seme" "$work/tampered-package.seme";printf x >> "$work/tampered-package.seme";if compose "$work/reject-tamper" "$work/tampered-package.seme" > "$work/tamper.out" 2> "$work/tamper.err";then exit 1;fi;test ! -e "$work/reject-tamper";test ! -s "$work/tamper.out"
sed 's/"dependencies":\["configuration"\]/"dependencies":["missing"]/' "$fixture/configuration-selection.json" > "$work/bad-selection.json";if compose "$work/reject-selection" "$work/package-v4.seme" "$work/bad-selection.json" > "$work/selection.out" 2> "$work/selection.err";then exit 1;fi;test ! -e "$work/reject-selection";test ! -s "$work/selection.out"
cp -R "$fixture" "$work/ambient";printf '\n/** @returns {string} */ export function Ambient() { return process.env.HOME; }\n' >> "$work/ambient/application.js";if (cd "$work/ambient"&&node "$repo/reference/js/javascript-package-provider-cli.mjs" --files application.js,configuration.js,policy.js --module "$repo/modules/execution/v36/module.g1" --package "$project" --entry Run --revision 2 --out "$work/ambient.g1") > "$work/ambient.out" 2> "$work/ambient.err";then exit 1;fi;test ! -e "$work/ambient.g1";test ! -s "$work/ambient.out"
if [ -n "${JS_UPB05_EXPORT:-}" ];then test ! -e "$JS_UPB05_EXPORT";mkdir "$JS_UPB05_EXPORT";cp -R "$work/bundle" "$JS_UPB05_EXPORT/bundle";cp "$work/snapshot.json" "$JS_UPB05_EXPORT/snapshot.json";cp "$work/graph.json" "$JS_UPB05_EXPORT/graph.json";fi
echo 'JavaScript UPB-05 foundation: neutral Configuration-v3 and Project-v8 authorities reproduce'
