#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd); fixture="$repo/fixtures/javascript-upb05-configuration"; project=example.test/javascript-upb05
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb05.XXXXXX");trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache";XDG_CACHE_HOME="$work/cache";export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && for command in project-source-discover project-assemble source-inventory-emit package-detail-emit package-v4-upgrade dependency-emit project-v8-compose;do go build -buildvcs=false -o "$work/$command" "./cmd/$command";done)
(cd "$fixture" && node "$repo/reference/js/javascript-package-provider-cli.mjs" --files application.js,configuration.js,policy.js --module "$repo/modules/execution/v36/module.g1" --package "$project" --entry Run --revision 1 --out "$work/construction.g1")
"$repo/bootstrap/seme-k0-linux-amd64" "$repo/compiler/g1-compiler.k0" "$work/construction.g1" "$work/execution.seme"
"$work/project-source-discover" -root "$fixture" -identity "$project" -language javascript -toolchain "$(node --version)" -profile seme.javascript-upb05/v1 -semantic-revision seme.javascript-provider/uab11 -tracked-extensions .js -generated-header '// Code generated' -out "$work/snapshot.json"
(cd "$fixture" && node "$repo/reference/js/javascript-project-graph-cli.mjs" --files application.js,configuration.js,policy.js --snapshot "$work/snapshot.json" --canonical-g1 "$work/construction.g1" --project "$project" --root-module application.js --out "$work/graph.json")
node "$repo/reference/js/javascript-project-manifest-cli.mjs" --project "$project" --graph "$work/graph.json" --out "$work/manifest.json"
"$work/project-assemble" -execution "$work/execution.seme" -manifest "$work/manifest.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/project-base.seme"
"$work/source-inventory-emit" -snapshot "$work/snapshot.json" -project "$work/project-base.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/inventory.seme"
"$work/package-detail-emit" -base "$work/project-base.seme" -inventory "$work/inventory.seme" -graph "$work/graph.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v2.seme"
"$work/package-v4-upgrade" -package "$work/package-v2.seme" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -out "$work/package-v4.seme"
node "$repo/reference/js/javascript-npm-resolver-cli.mjs" --manifest "$fixture/package.json" --lock "$fixture/package-lock.json" --local-root "$fixture" --local-files configuration.js,policy.js --external-root "$repo/fixtures/javascript-upb03-external-checksum" --external-files index.js,package.json --local-identity "$project/configuration" --local-from "$project/application" --external-source file:../javascript-upb03-external-checksum --out "$work/closure.json"
"$work/dependency-emit" -closure "$work/closure.json" -contract "$repo/modules/dependency/v1/module.seme" -out "$work/dependency.seme"
compose(){ "$work/project-v8-compose" -construction "$work/construction.g1" -project-base "$work/project-base.seme" -inventory "$work/inventory.seme" -package-v2 "$work/package-v2.seme" -package-v4 "$work/package-v4.seme" -dependency "$work/dependency.seme" -selection "$fixture/configuration-selection.json" -foundation-contract "$repo/modules/foundation/v1/module.seme" -execution-contract "$repo/modules/execution/v36/module.seme" -package-contract "$repo/modules/package/v4/module.seme" -dependency-contract "$repo/modules/dependency/v1/module.seme" -configuration-contract "$repo/modules/configuration/v3/module.seme" -project-contract "$repo/modules/project/v8/module.seme" -k0 "$repo/bootstrap/seme-k0-linux-amd64" -g1-compiler "$repo/compiler/g1-compiler.k0" -out "$1";}
compose "$work/v8-a";compose "$work/v8-b";cmp "$work/v8-a/configuration-v3.seme" "$work/v8-b/configuration-v3.seme";cmp "$work/v8-a/project-v8.seme" "$work/v8-b/project-v8.seme"
echo 'JavaScript UPB-05 foundation: neutral Configuration-v3 and Project-v8 authorities reproduce'
