#!/bin/sh
set -eu
repo=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
work=$(mktemp -d "${TMPDIR:-/tmp}/seme-javascript-upb01-source.XXXXXX")
trap 'rm -rf "$work"' EXIT HUP INT TERM
GOCACHE="$work/go-cache"; XDG_CACHE_HOME="$work/cache"; export GOCACHE XDG_CACHE_HOME
(cd "$repo/reference/go" && go build -buildvcs=false -o "$work/discover" ./cmd/project-source-discover)
cp -R "$repo/fixtures/javascript-uab-01" "$work/project"
mkdir "$work/project/generated" "$work/project/ignored" "$work/project/vendor"
printf '%s\n' '// Code generated by fixture; DO NOT EDIT.' 'export const generated = 1;' > "$work/project/generated/value.js"
printf '%s\n' 'ignored cache' > "$work/project/ignored/cache.bin"
printf '%s\n' 'ignored suffix' > "$work/project/local.tmp"
printf '%s\n' 'vendored notice' > "$work/project/vendor/NOTICE"
printf '%s\n' 'opaque project note' > "$work/project/README.md"

discover() {
  "$work/discover" -root "$work/project" -identity example.test/javascript-upb01 \
    -language javascript -toolchain "$(node --version)" \
    -profile seme.javascript-upb01/v1 \
    -semantic-revision seme.javascript-provider/uab11 \
    -tracked-extensions .js -ignored-prefixes ignored/ \
    -ignored-suffixes .tmp -vendored-prefixes vendor/ \
    -generated-header '// Code generated' -out "$1"
}
discover "$work/a.json"
discover "$work/b.json"
cmp "$work/a.json" "$work/b.json"
node -e '
const s=JSON.parse(require("fs").readFileSync(process.argv[1]));
const got=Object.fromEntries(s.Units.map(u=>[u.Path,[u.Class,u.Preservation]]));
const want={"README.md":["opaque","byte-exact"],"application.js":["tracked","semantic-projection"],"generated/value.js":["generated","byte-exact"],"ignored/cache.bin":["ignored","byte-exact"],"local.tmp":["ignored","byte-exact"],"math/sum.js":["tracked","semantic-projection"],"vendor/NOTICE":["vendored","byte-exact"]};
if(JSON.stringify(got)!==JSON.stringify(want)||!/^[0-9a-f]{64}$/.test(s.ContentRevision)) process.exit(1);
' "$work/a.json"

if discover "$work/a.json" >"$work/collision.out" 2>"$work/collision.err"; then exit 1; fi
grep -q 'project_source_discover.output_exists' "$work/collision.err"
ln -s application.js "$work/project/alias.js"
if discover "$work/rejected.json" >"$work/symlink.out" 2>"$work/symlink.err"; then exit 1; fi
grep -q 'project_source.symlink:alias.js' "$work/symlink.err"
test ! -e "$work/rejected.json"

echo 'JavaScript UPB-01 source inventory foundation: deterministic classification and atomic adversaries pass'
