local source = debug.getinfo(1, "S").source
local directory = assert(source:match("^@(.*/)"), "test source path unavailable")
local Seme = dofile(directory .. "seme-values.lua")

local minimum = Seme.i64("-9223372036854775808")
local maximum = Seme.i64("9223372036854775807")
assert(Seme.kind(minimum) == "i64" and Seme.kind(maximum) == "i64")
assert(not pcall(Seme.i64, "9223372036854775808"))
assert(Seme.i64_decimal(Seme.multiply(Seme.i64("9223372036854775807"), Seme.i64("2"))) == "-2")
assert(Seme.kind(Seme.text("snow: \233\155\170")) == "text")
assert(Seme.kind(Seme.bytes("\255\000")) == "bytes")

local none, some = Seme.none(), Seme.some(maximum)
assert(not Seme.option_is_some(none) and Seme.option_is_some(some))
assert(Seme.option_value(some) == maximum)
assert(not pcall(Seme.option_value, none))
assert(Seme.result_is_ok(Seme.ok(maximum)))
assert(not Seme.result_is_ok(Seme.err(Seme.text("bad"))))

local array = Seme.array(2, { minimum, maximum })
local slice = Seme.slice({ maximum })
assert(Seme.collection_length(array) == 2)
assert(Seme.collection_get(array, 0) == minimum)
assert(Seme.collection_get(slice, 0) == maximum)
assert(not pcall(Seme.collection_get, array, 2))
assert(not pcall(Seme.slice, { [1] = minimum, [3] = maximum }))
local appended = Seme.collection_append(slice, minimum)
assert(Seme.length(slice) == 1 and Seme.length(appended) == 2 and Seme.index_zero(appended, 1) == minimum)
local replaced = Seme.collection_update(appended, Seme.i64("0"), minimum)
assert(Seme.index_zero(appended, 0) == maximum and Seme.index_zero(replaced, 0) == minimum)
local removed = Seme.slice_remove(appended, Seme.i64("0"))
assert(Seme.length(removed) == 1 and Seme.index_zero(removed, 0) == minimum)
assert(Seme.i64_decimal(Seme.fold(appended, Seme.i64("0"), Seme.add)) == "-1")
assert(not pcall(Seme.collection_update, appended, Seme.i64("2"), minimum))
assert(not pcall(Seme.slice_remove, appended, Seme.i64("2")))

local record = Seme.record("Bounds", { "minimum", "maximum" }, { minimum = minimum, maximum = maximum })
assert(Seme.record_get(record, "minimum") == minimum)
assert(not pcall(Seme.record, "Bad", { "value" }, { value = maximum, extra = minimum }))

local map = Seme.map("i64", { { key = Seme.text("b"), value = maximum }, { key = Seme.text("a"), value = minimum } })
assert(Seme.option_value(Seme.map_lookup(map, Seme.text("a"))) == minimum)
assert(not Seme.option_is_some(Seme.map_lookup(map, Seme.text("missing"))))
assert(not pcall(Seme.map, { { key = Seme.text("a"), value = minimum }, { key = Seme.text("a"), value = maximum } }))

assert(not pcall(function() array[1] = maximum end))
local constructed = Seme.array(minimum, maximum)
assert(Seme.length(constructed) == 2 and Seme.index_zero(constructed, 1) == maximum)
local updated = Seme.map_update(Seme.empty_map("i64"), Seme.text("key"), minimum)
assert(Seme.option_value(Seme.map_lookup(updated, Seme.text("key"))) == minimum)
assert(Seme.kind(Seme.lookup_zero(updated, Seme.text("missing"))) == "i64")
assert(Seme.kind(Seme.lookup_zero(Seme.empty_map("text"), Seme.text("missing"))) == "text")
assert(Seme.kind(Seme.lookup_zero(Seme.empty_map("bytes"), Seme.text("missing"))) == "bytes")
assert(not pcall(Seme.lookup_zero, Seme.empty_map(), Seme.text("missing")))
local without = Seme.map_remove(updated, Seme.text("key"))
assert(Seme.option_is_some(Seme.map_lookup(updated, Seme.text("key"))) and not Seme.option_is_some(Seme.map_lookup(without, Seme.text("key"))))
assert(Seme.map_remove(without, Seme.text("missing")) ~= without) -- immutable no-op result
local function check(value)
  return Seme.match_option(value, false, function(some)
    return Seme.match_result(some,
      function(ok) return Seme.bytes_equal(ok, Seme.bytes_literal("ok")) end,
      function(err) return Seme.text_equal(err, "bad") end)
  end)
end
assert(check(Seme.none()) == false)
assert(check(Seme.some(Seme.ok(Seme.bytes("ok")))) == true)
assert(check(Seme.some(Seme.ok(Seme.bytes("no")))) == false)
assert(check(Seme.some(Seme.err(Seme.text("bad")))) == true)
assert(check(Seme.some(Seme.err(Seme.text("other")))) == false)
local requirement_source = { "adjust" }
local method_source = {
  adjust = function(receiver, value) return Seme.add(receiver, value) end,
}
local adjuster = Seme.protocol("Adjuster", requirement_source)
local offset = Seme.implementation(adjuster, "i64", method_source)
local boxed = Seme.interface_value(offset, Seme.i64("4"))
assert(Seme.i64_decimal(Seme.dynamic_call(boxed, "adjust", Seme.i64("3"))) == "7")
requirement_source[1], method_source.adjust = "changed", function() error("mutated source") end
assert(Seme.i64_decimal(Seme.dynamic_call(boxed, "adjust", Seme.i64("3"))) == "7")
assert(not pcall(Seme.implementation, adjuster, "i64", {}))
assert(not pcall(Seme.implementation, adjuster, "i64", { adjust = function() end, extra = function() end }))
assert(not pcall(Seme.interface_value, offset, Seme.text("4")))
assert(not pcall(Seme.dynamic_call, boxed, "missing", Seme.i64("3")))
assert(Seme.i64_decimal(Seme.immutable_closure_run(Seme.i64("5"), Seme.i64("7"))) == "12")
assert(Seme.i64_decimal(Seme.mutable_closure_run(Seme.i64("10"), Seme.i64("3"), Seme.i64("4"))) == "17")
assert(Seme.i64_decimal(Seme.mutable_closure_run(Seme.i64("9223372036854775807"), Seme.i64("1"), Seme.i64("1"))) == "-9223372036854775807")
local counter = Seme.record("Counter", {"Value"}, {Value=Seme.i64("10")})
local transition = Seme.transition_step(counter, Seme.i64("3"), "Value")
assert(Seme.i64_decimal(Seme.record_get(Seme.transition_state(transition), "Value")) == "13")
assert(Seme.i64_decimal(Seme.transition_result(transition)) == "10")
local generic_transition = Seme.transition(counter, maximum)
assert(Seme.transition_state(generic_transition) == counter and Seme.transition_result(generic_transition) == maximum)
assert(not pcall(Seme.transition_state, counter))
local success = Seme.increment_positive(Seme.i64("4"))
assert(Seme.result_is_ok(success) and Seme.i64_decimal(Seme.result_value(success)) == "5")
local propagated = Seme.increment_positive(Seme.i64("-7"))
assert(not Seme.result_is_ok(propagated) and Seme.i64_decimal(Seme.result_value(propagated)) == "99")
local observations = {}
_G.Seme_observability_log = function(value) table.insert(observations, value) end
Seme.observe(true); Seme.observe(false)
assert(observations[1] == true and observations[2] == false)
_G.Seme_observability_log = nil
assert(not pcall(Seme.observe, true))
print("Lua compound adapter foundation: ok")
