local source = debug.getinfo(1, "S").source
local directory = assert(source:match("^@(.*/)"), "test source path unavailable")
local Seme = dofile(directory .. "seme-values.lua")

local minimum = Seme.i64("-9223372036854775808")
local maximum = Seme.i64("9223372036854775807")
assert(Seme.kind(minimum) == "i64" and Seme.kind(maximum) == "i64")
assert(not pcall(Seme.i64, "9223372036854775808"))
assert(Seme.kind(Seme.text("snow: \233\155\170")) == "text")
assert(Seme.kind(Seme.bytes("\255\000")) == "bytes")

local none, some = Seme.none(), Seme.some(maximum)
assert(not Seme.option_is_some(none) and Seme.option_is_some(some))
assert(Seme.option_value(some) == maximum)
assert(not pcall(Seme.option_value, none))
assert(Seme.result_is_ok(Seme.ok(maximum)))
assert(not Seme.result_is_ok(Seme.err(Seme.text("bad"))))

local array = Seme.array(2, { minimum, maximum })
local slice = Seme.slice({ maximum })
assert(Seme.collection_length(array) == 2)
assert(Seme.collection_get(array, 0) == minimum)
assert(Seme.collection_get(slice, 0) == maximum)
assert(not pcall(Seme.collection_get, array, 2))
assert(not pcall(Seme.slice, { [1] = minimum, [3] = maximum }))

local record = Seme.record("Bounds", { "minimum", "maximum" }, { minimum = minimum, maximum = maximum })
assert(Seme.record_get(record, "minimum") == minimum)
assert(not pcall(Seme.record, "Bad", { "value" }, { value = maximum, extra = minimum }))

local map = Seme.map("i64", { { key = Seme.text("b"), value = maximum }, { key = Seme.text("a"), value = minimum } })
assert(Seme.option_value(Seme.map_lookup(map, Seme.text("a"))) == minimum)
assert(not Seme.option_is_some(Seme.map_lookup(map, Seme.text("missing"))))
assert(not pcall(Seme.map, { { key = Seme.text("a"), value = minimum }, { key = Seme.text("a"), value = maximum } }))

assert(not pcall(function() array[1] = maximum end))
local constructed = Seme.array(minimum, maximum)
assert(Seme.length(constructed) == 2 and Seme.index_zero(constructed, 1) == maximum)
local updated = Seme.map_update(Seme.empty_map("i64"), Seme.text("key"), minimum)
assert(Seme.option_value(Seme.map_lookup(updated, Seme.text("key"))) == minimum)
assert(Seme.kind(Seme.lookup_zero(updated, Seme.text("missing"))) == "i64")
assert(Seme.kind(Seme.lookup_zero(Seme.empty_map("text"), Seme.text("missing"))) == "text")
assert(Seme.kind(Seme.lookup_zero(Seme.empty_map("bytes"), Seme.text("missing"))) == "bytes")
assert(not pcall(Seme.lookup_zero, Seme.empty_map(), Seme.text("missing")))
local function check(value)
  return Seme.match_option(value, false, function(some)
    return Seme.match_result(some,
      function(ok) return Seme.bytes_equal(ok, Seme.bytes_literal("ok")) end,
      function(err) return Seme.text_equal(err, "bad") end)
  end)
end
assert(check(Seme.none()) == false)
assert(check(Seme.some(Seme.ok(Seme.bytes("ok")))) == true)
assert(check(Seme.some(Seme.ok(Seme.bytes("no")))) == false)
assert(check(Seme.some(Seme.err(Seme.text("bad")))) == true)
assert(check(Seme.some(Seme.err(Seme.text("other")))) == false)
print("Lua compound adapter foundation: ok")
